import {
  buildChoice, buildCollocationLock, buildErrorHunt, buildExplainWhy, buildFreeRewrite,
  buildInput, buildOddOneOut, buildOrder, buildSynonymPick, buildTextOrder, buildTransform,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";
import {
  buildCollocationLock as lexicalCollocation, buildOddOneOut as lexicalOdd,
  buildSynonymPick as lexicalSynonym, LEXICAL_BANKS,
} from "../../lexicalBanks.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 3): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 760) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });
const prep = (id: string) => {
  const entry = LEXICAL_BANKS.governedPrepositions.find((candidate) => candidate.id === id);
  if (!entry) throw new Error(`Missing governed preposition ${id}`);
  return entry;
};
const falseFriend = (id: string) => {
  const entry = LEXICAL_BANKS.falseFriends.find((candidate) => candidate.id === id);
  if (!entry) throw new Error(`Missing false friend ${id}`);
  return entry;
};
const decision = lexicalCollocation("col-traeffe-beslutning");
const precedent = lexicalCollocation("col-skabe-praecedens");
const evidenceField = lexicalOdd("field-evidence");
const reportingWord = lexicalSynonym("syn-say-neutral-report");
const dependence = prep("prep-afhaengig-af");
const distinction = prep("prep-skelne-mellem");
const actual = falseFriend("false-aktuel");
const form = falseFriend("false-blanket");

export const level17: CourseLevel = {
  id: "level-17", eyebrow: "B2 · Niveau 17", title: "Ord der hører sammen",
  description: "Lås ordene sammen, som dansk faktisk gør — ikke som en ordbog og et håb foreslår.",
  color: "#af79d4", unlockXp: 19400,
  missions: [
    mission("l17-m01", "Sprogets tandhjul", "Verbum og substantiv som faste arbejdspartnere", "layers", [
      buildCollocationLock({ ...common("l17-m01-q01", `${decision.promptDa} ${decision.contextDa}`, decision.answerDa, "Choose the verb that collocates with 'a decision'.", "kollokationer", ["collocation-lock", decision.id], "Dansk træffer en beslutning; det bygger den ikke.", "Kollokationen er fast nok til, at et ellers forståeligt verbum lyder fremmed."), anchor: "en beslutning", options: [...decision.optionsDa], relation: "verb-noun" }),
      buildCollocationLock({ ...common("l17-m01-q02", `${precedent.promptDa} ${precedent.contextDa}`, precedent.answerDa, "Choose the verb that collocates with 'precedent'.", "kollokationer", ["collocation-lock", precedent.id], "Tænk på, at handlingen skaber en fremtidig norm.", "Skabe præcedens er den konventionelle juridiske kollokation."), anchor: "præcedens", options: [...precedent.optionsDa], relation: "verb-noun" }),
      buildChoice({ ...common("l17-m01-q03", "Vælg den idiomatiske kombination.", "rejse kritik", "raise criticism", "kollokationer", ["verb-noun", "kritik"], "Kritik bliver ikke løftet med hænderne, men verbet er stadig rejse.", "Rejse kritik er en etableret kollokation i formelt dansk."), options: ["bygge kritik", "rejse kritik", "koge kritik", "skyde kritik"] }),
      buildErrorHunt({ ...common("l17-m01-q04", "Find kollokationsfejlen, og ret verbet.", "drager", "The committee draws a cautious conclusion.", "kollokationer", ["error-hunt", "konklusion"], "Konklusionen skal udledes, ikke fremstilles på en fabrik.", "Drage en konklusion er den faste formelle forbindelse.", "produce"), sentenceTokens: ["Udvalget", "laver", "en", "forsigtig", "konklusion."], errorIndex: 1, correction: "drager" }),
      buildOrder({ ...common("l17-m01-q05", "Byg sætningen med to naturlige kollokationer.", "Rapporten rejser tvivl og lægger pres på ledelsen.", "The report raises doubt and puts pressure on management.", "kollokationer", ["rejse-tvivl", "lægge-pres"], "Hvert substantiv kræver sit eget partnerverbum.", "Rejse tvivl og lægge pres på er to selvstændige, konventionelle forbindelser.", "produce"), tokens: ["Rapporten", "rejser tvivl", "og lægger pres", "på ledelsen."], acceptedAnswers: ["Rapporten rejser tvivl og lægger pres på ledelsen."] }),
      buildInput({ ...common("l17-m01-q06", "Udfyld: Tilsynet vil ___ en undersøgelse af sagen.", "iværksætte", "The regulator will initiate an investigation into the case.", "kollokationer", ["iværksætte", "undersøgelse"], "Vælg et formelt verbum for at sætte processen i gang.", "Iværksætte en undersøgelse er præcist myndighedssprog.", "produce"), acceptedAnswers: ["iværksætte", "Iværksætte"] }),
      buildOddOneOut({ ...common("l17-m01-q07", evidenceField.promptDa, evidenceField.answerDa, "Find the word that does not belong to evidence terminology.", "semantiske felter", ["odd-one-out", evidenceField.id], "Tre ord kan indgå i en efterforskning som materiale.", evidenceField.explanationEn), family: "bevismateriale", options: [...evidenceField.optionsDa], reason: evidenceField.explanationEn }),
      buildFreeRewrite({ ...common("l17-m01-q08", "Omskriv notatet med mindst fire præcise kollokationer.", "AI-bedømt omskrivning", "Rewrite the note using at least four precise Danish collocations.", "kollokationer", ["free-rewrite", "formelt-register"], "Erstat gøre/lave med forbindelser som træffe, rejse, drage og tage.", "Svaret vurderes på idiomatiske kollokationer, sammenhæng og bevaret betydning.", "produce"), sourceText: "Udvalget laver en beslutning, laver kritik, laver en konklusion og gør ansvar for fejlen.", instruction: "Skriv et naturligt formelt notat med mindst fire korrekte kollokationer.", minWords: 28, aiPolicy: { mode: "grade", task: "free-rewrite", skipWhenUnavailable: true, requiredFacts: ["træffe en beslutning", "rejse kritik", "drage en konklusion", "tage ansvar"] } }),
    ]),
    mission("l17-m02", "Præpositionens kontrakt", "Ord styrer små ord med store konsekvenser", "target", [
      buildCollocationLock({ ...common("l17-m02-q01", `Vælg præpositionen: ${dependence.exampleDa.replace(dependence.prepositionDa, "___")}`, dependence.prepositionDa, "Choose the governed preposition after 'dependent'.", "styrede præpositioner", ["collocation-lock", dependence.id], "Afhængig indgår en fast forbindelse.", "Afhængig styrer af, uanset hvad engelsk eller mavefornemmelsen foreslår."), anchor: dependence.headDa, options: [dependence.prepositionDa, ...dependence.distractorsDa], relation: "adjective-preposition" }),
      buildCollocationLock({ ...common("l17-m02-q02", `Vælg præpositionen: ${distinction.exampleDa.replace(distinction.prepositionDa, "___")}`, distinction.prepositionDa, "Choose the governed preposition after 'distinguish'.", "styrede præpositioner", ["collocation-lock", distinction.id], "Der er to kategorier, som holdes adskilt.", "Skelne styrer mellem, når forskellen mellem to ting beskrives."), anchor: distinction.headDa, options: [distinction.prepositionDa, ...distinction.distractorsDa], relation: "verb-preposition" }),
      buildChoice({ ...common("l17-m02-q03", "Vælg: Bestyrelsen skal tage stilling ___ forslaget.", "til", "The board must take a position on the proposal.", "styrede præpositioner", ["tage-stilling-til"], "Hele udtrykket er en fast forbindelse.", "Tage stilling styrer til."), options: ["af", "på", "til", "med"] }),
      buildErrorHunt({ ...common("l17-m02-q04", "Find og ret den styrede præposition.", "mod", "The coating protects the steel against salt water.", "styrede præpositioner", ["error-hunt", "beskytte-mod"], "Beskyttelse retter sig imod en trussel.", "Beskytte styrer mod, mens for ville markere formål eller modtager.", "produce"), sentenceTokens: ["Belægningen", "beskytter", "stålet", "for", "saltvand."], errorIndex: 3, correction: "mod" }),
      buildInput({ ...common("l17-m02-q05", "Udfyld: Hun insisterede ___ at se de originale bilag.", "på", "She insisted on seeing the original attachments.", "styrede præpositioner", ["insistere-på"], "Verbet kræver samme præposition foran en at-infinitiv.", "Insistere på at er den faste konstruktion.", "produce"), acceptedAnswers: ["på", "På"] }),
      buildOrder({ ...common("l17-m02-q06", "Byg sætningen med tre styrede forbindelser.", "Vi tvivler på svaret, henviser til bilaget og advarer mod hastværk.", "We doubt the answer, refer to the appendix, and warn against haste.", "styrede præpositioner", ["tvivle-på", "henvise-til", "advare-mod"], "Bevar præpositionen til hvert af de tre verber.", "Tvivle på, henvise til og advare mod er uafhængige styringsmønstre.", "produce"), tokens: ["Vi tvivler på svaret,", "henviser til bilaget", "og advarer mod hastværk."], acceptedAnswers: ["Vi tvivler på svaret, henviser til bilaget og advarer mod hastværk."] }),
      buildTransform({ ...common("l17-m02-q07", "Ret alle tre præpositioner.", "Hun bidrager til projektet, deltager i mødet og sørger for kaffen.", "She contributes to the project, attends the meeting, and takes care of the coffee.", "styrede præpositioner", ["transform", "præpositioner"], "Lær forbindelserne som hele enheder.", "Bidrage til, deltage i og sørge for har hver sin styrede præposition.", "produce"), sourceSentence: "Hun bidrager på projektet, deltager på mødet og sørger om kaffen.", instruction: "Ret kun præpositionerne.", acceptedAnswers: ["Hun bidrager til projektet, deltager i mødet og sørger for kaffen."] }),
      buildExplainWhy({ ...common("l17-m02-q08", "Forklar, hvorfor styrede præpositioner bør læres som fraser.", "AI-bedømt forklaring", "Explain why governed prepositions should be learned as phrases.", "styrede præpositioner", ["explain-why", "læringsstrategi"], "Sammenlign grammatisk regel med leksikalsk vane.", "Forklaringen vurderes på vilkårlighed, chunking og brug af mindst to danske eksempler.", "produce"), claim: "At kende ordet ‘afhængig’ er ikke nok til sikkert at bruge det.", requiredConcepts: ["leksikalsk styring", "hele fraser", "eksempler"], minWords: 55, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["præpositionen kan ikke altid udledes", "fraser reducerer fejl", "mindst to eksempler"] } }),
    ], 780),
    mission("l17-m03", "Venner med falske pas", "False friends og kontekstkontrol", "sparkles", [
      buildChoice({ ...common("l17-m03-q01", `Hvad betyder “${actual.danishDa}” i: ${actual.exampleDa}`, actual.meaningEn, "Choose the actual English meaning of the Danish false friend.", "false friends", ["false-friend", actual.id], "Lad være med at oversætte ud fra ordets engelske udseende.", actual.trapEn), options: [actual.meaningEn, actual.temptingEnglish, "ancient", "accidental"] }),
      buildChoice({ ...common("l17-m03-q02", `Hvad betyder “${form.danishDa}” i: ${form.exampleDa}`, form.meaningEn, "Choose the English meaning of the Danish word.", "false friends", ["false-friend", form.id], "Kontoret beder dig ikke om sengetøj.", form.trapEn), options: [form.temptingEnglish, form.meaningEn, "blank space", "carpet"] }),
      buildErrorHunt({ ...common("l17-m03-q03", "Find den falske ven i den engelske betydning og ret det danske ord.", "stof", "The curtains are made of heavy fabric.", "false friends", ["error-hunt", "fabrik"], "En bygning producerer varer; et materiale hænger foran vinduet.", "Fabrik betyder factory; stof er fabric i denne sammenhæng.", "produce"), sentenceTokens: ["Gardinerne", "er", "lavet", "af", "tung", "fabrik."], errorIndex: 5, correction: "stof" }),
      buildChoice({ ...common("l17-m03-q04", "Hvad betyder “eventuelt” i mødeplanen: “Vi tager eventuelt punktet fredag” ?", "possibly, if needed", "possibly, if needed", "false friends", ["eventuelt", "modalitet"], "Det siger ikke, at noget sker til sidst.", "Eventuelt betyder possibly/if appropriate, ikke eventually."), options: ["eventually", "possibly, if needed", "immediately", "formally"] }),
      buildInput({ ...common("l17-m03-q05", "Udfyld det danske ord for boss: Min ___ godkendte ferien.", "chef", "My boss approved the holiday.", "false friends", ["chef", "arbejde"], "På dansk står personen ikke nødvendigvis i et køkken.", "Chef betyder leder; en chefkok er en særlig køkkenrolle.", "produce"), acceptedAnswers: ["chef", "Chef"] }),
      buildOrder({ ...common("l17-m03-q06", "Byg en sætning, der afslører to falske venner uden forklaring.", "Min chef spiste frokost på kontoret.", "My boss ate lunch at the office.", "false friends", ["chef", "frokost", "kontor"], "Alle tre substantiver ligner mere på engelsk, end de betyder.", "Konteksten gør chef, frokost og kontor entydige som boss, lunch og office.", "produce"), tokens: ["Min chef", "spiste frokost", "på kontoret."], acceptedAnswers: ["Min chef spiste frokost på kontoret."] }),
      buildTextOrder({ ...common("l17-m03-q07", "Ordne forklaringen, så den går fra fælde til sikker strategi.", "a>b>c>d>e", "Order the explanation from trap to safe strategy.", "tekstsammenhæng", ["text-order", "false-friends"], "Begynd med ligheden, og slut med en aktiv kontrolmetode.", "Teksten viser først fristelsen, derefter fejlen, konteksten, rettelsen og en strategi.", "produce"), sentences: [{ id: "a", text: "Nogle danske ord ligner engelske ord meget." }, { id: "b", text: "Derfor vælger hjernen ofte den hurtigste oversættelse." }, { id: "c", text: "Men sætningens kontekst kan gøre den oversættelse umulig." }, { id: "d", text: "Så må betydningen kontrolleres som dansk, ikke som stavning." }, { id: "e", text: "Lær til sidst ordet sammen med et kort eksempel." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["d", "a", "e", "c", "b"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildChoice({ ...common("l17-m03-q08", "Hvilken reklame bruger med vilje en dum falsk-ven-vittighed, men er stadig forståelig?", "Vores fabrik laver stof — den er altså ikke lavet af fabric.", "Our factory makes fabric — it is not made of fabric.", "false friends", ["humor", "fabrik"], "Ordspillet skal bygge på en ægte betydningsforskel.", "Vittigheden kontrasterer dansk fabrik med engelsk fabric og leverer samtidig den korrekte oplysning."), options: ["Vores fabrik laver stof — den er altså ikke lavet af fabric.", "Alle ord betyder det samme, hæhæ.", "Frokost er breakfast, hvis man er modig."] }),
    ], 800),
    mission("l17-m04", "Den præcise nerve", "Nuance, register og længere argumenter", "star", [
      buildSynonymPick({ ...common("l17-m04-q01", `${reportingWord.promptDa} ${reportingWord.contextDa}`, reportingWord.answerDa, "Choose the synonym that fits neutral reporting.", "synonymer", ["synonym-pick", reportingWord.id], "Vælg ordet, der tilskriver information uden drama.", "Det valgte bankord passer i journalistisk register og bevarer en neutral styrke."), focusWord: "siger", context: reportingWord.contextDa, register: "formal", options: [...reportingWord.optionsDa] }),
      buildSynonymPick({ ...common("l17-m04-q02", "Vælg det præcise ord: Dataene ___ en sammenhæng, men beviser ikke årsagen.", "indikerer", "The data indicate an association but do not prove causation.", "synonymer", ["synonym-pick", "evidens"], "Styrken skal være lavere end beviser.", "Indikerer peger på et mønster uden at gøre det kausalt sikkert."), focusWord: "viser", context: "Dataene ___ en sammenhæng, men beviser ikke årsagen.", register: "formal", options: ["indikerer", "beviser", "skriger", "afslører"] }),
      buildChoice({ ...common("l17-m04-q03", "Hvilket ord er skarpest uden at blive vulgært?", "vildledende", "misleading", "nuance", ["register", "kritik"], "Kritiser udsagnets virkning, ikke talerens menneskeværd.", "Vildledende er en alvorlig, præcis kritik af kommunikationen."), options: ["lidt mærkeligt", "vildledende", "megaåndssvagt", "perfekt"] }),
      buildErrorHunt({ ...common("l17-m04-q04", "Find ordet, der overdriver evidensen.", "tyder på", "The figures suggest a systematic error.", "nuance", ["error-hunt", "evidensstyrke"], "Tallene er få og foreløbige.", "Tyder på kalibrerer konklusionen; beviser ville være for kategorisk.", "produce"), sentenceTokens: ["De", "foreløbige", "tal", "beviser", "en", "systematisk", "fejl."], errorIndex: 3, correction: "tyder på" }),
      buildOrder({ ...common("l17-m04-q05", "Byg den bidende, men dokumenterede kritik.", "Forslaget er elegant formuleret, men praktisk uigennemførligt.", "The proposal is elegantly worded but practically impossible to implement.", "register", ["kontrast", "kritik"], "Ros formen, og skær derefter ind til funktionens problem.", "Kontrasten er skarp, men vurderingen knyttes til konkrete egenskaber.", "produce"), tokens: ["Forslaget er", "elegant formuleret,", "men praktisk", "uigennemførligt."], acceptedAnswers: ["Forslaget er elegant formuleret, men praktisk uigennemførligt."] }),
      buildTransform({ ...common("l17-m04-q06", "Omskriv angrebet til hård, saglig kritik.", "Argumentet bygger på en udokumenteret antagelse og ignorerer de modsatrettede data.", "The argument rests on an unsupported assumption and ignores the conflicting data.", "register", ["transform", "saglig-kritik"], "Behold styrken, men ret den mod argumentets struktur.", "Den nye version navngiver to efterprøvelige svagheder uden personangreb.", "produce"), sourceSentence: "Forfatteren er en idiot, og hele teksten er skrald.", instruction: "Gør kritikken professionel uden at gøre den mild.", acceptedAnswers: ["Argumentet bygger på en udokumenteret antagelse og ignorerer de modsatrettede data."] }),
      buildTextOrder({ ...common("l17-m04-q07", "Sæt den længere analyse i en overbevisende rækkefølge.", "a>b>c>d>e>f", "Order the longer analysis persuasively.", "argumentation", ["text-order", "kollokationer"], "Gå fra påstand til grundlag, begrænsning og konsekvens.", "Strukturen etablerer sagen, dokumenterer, afgrænser og ender i en proportionel anbefaling.", "produce"), sentences: [{ id: "a", text: "Rapporten rejser alvorlig kritik af kontrollen." }, { id: "b", text: "Tre uafhængige målinger viser samme fejl." }, { id: "c", text: "Materialet danner derfor et stærkt grundlag for handling." }, { id: "d", text: "Det fastslår dog ikke, hvem der ændrede systemet." }, { id: "e", text: "Ledelsen bør iværksætte en undersøgelse frem for at udpege en syndebuk." }, { id: "f", text: "Sådan tager den ansvar uden at foregive sikkerhed." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["d", "f", "b", "a", "e", "c"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildFreeRewrite({ ...common("l17-m04-q08", "Skriv en kort redaktionel afslutning med præcise ordforbindelser.", "AI-bedømt omskrivning", "Write a short editorial conclusion using precise collocations.", "argumentation", ["free-rewrite", "kollokationer", "nuance"], "Brug mindst tre kollokationer og én tydelig begrænsning.", "Svaret vurderes på naturlige ordforbindelser, register, dokumenteret skarphed og kalibreret konklusion.", "produce"), sourceText: "Dokumenterne peger på alvorlige fejl, men den ansvarlige person er endnu ukendt.", instruction: "Skriv 55–85 ord med mindst tre kollokationer og uden personangreb.", minWords: 55, aiPolicy: { mode: "grade", task: "free-rewrite", skipWhenUnavailable: true, requiredFacts: ["alvorlige fejl", "ansvarlig ukendt", "undersøgelse nødvendig", "mindst én begrænsning"] } }),
    ], 820),
  ],
};
