import {
  buildChoice, buildCompress, buildCounterfactualChain, buildErrorHunt, buildExplainWhy,
  buildInput, buildMicroDialogue, buildOrder, buildTextOrder, buildTransform,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 3): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 860) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });

export const level19: CourseLevel = {
  id: "level-19", eyebrow: "B1+ · Niveau 19", title: "Hvis det var gået anderledes",
  description: "Kortlæg fortidens ubrugte veje: hvad der kunne, burde og aldrig skulle være sket.",
  color: "#4f86c6", unlockXp: 25500,
  missions: [
    mission("l19-m01", "Den lukkede vej", "Pluskvamperfektum og uvirkelig fortid", "map", [
      buildChoice({ ...common("l19-m01-q01", "Vælg: Hvis hun ___ beskeden, var hun kommet tidligere.", "havde set", "If she had seen the message, she would have arrived earlier.", "irrealis", ["hvis", "pluskvamperfektum"], "Betingelsen ligger i en fortid, som ikke blev virkelig.", "Havde set markerer den uopfyldte fortidsbetingelse."), options: ["så", "havde set", "ville se", "ser"] }),
      buildOrder({ ...common("l19-m01-q02", "Byg den uvirkelige fortid.", "Hvis vi havde kontrolleret ventilen, var lækagen blevet opdaget.", "If we had checked the valve, the leak would have been discovered.", "irrealis", ["hvis", "førdatid"], "Begge handlinger ses bagud fra en senere fortid.", "Havde kontrolleret udtrykker den manglende årsag; var blevet opdaget udtrykker den udeblevne følge.", "produce"), tokens: ["Hvis vi", "havde kontrolleret ventilen,", "var lækagen", "blevet opdaget."], acceptedAnswers: ["Hvis vi havde kontrolleret ventilen, var lækagen blevet opdaget."] }),
      buildErrorHunt({ ...common("l19-m01-q03", "Find den tid, der gør betingelsen virkelig i stedet for kontrafaktisk.", "havde haft", "If the team had had more time, it would have tested the backup.", "irrealis", ["error-hunt", "pluskvamperfektum"], "Hold hele betingelsen i den uvirkelige fortid.", "Havde haft er førdatid; havde tid kan læses som simpel fortid.", "produce"), sentenceTokens: ["Hvis", "holdet", "havde", "mere", "tid,", "ville", "det", "have", "testet", "reserven."], errorIndex: 2, correction: "havde haft" }),
      buildInput({ ...common("l19-m01-q04", "Udfyld: Hvis døren ikke var gået i baglås, ___ vi være sluppet ud.", "kunne", "If the door had not jammed, we could have got out.", "modal perfektum", ["kunne-have"], "Følgen beskriver en mistet mulighed.", "Kunne have udtrykker evne eller mulighed, som ikke blev realiseret.", "produce"), acceptedAnswers: ["kunne", "Kunne"] }),
      buildCounterfactualChain({ ...common("l19-m01-q05", "Byg årsagskæden af de tre tabte muligheder.", "Hvis alarmen havde virket, havde vagten reageret, og branden var blevet begrænset.", "If the alarm had worked, the guard would have reacted, and the fire would have been contained.", "kontrafaktisk kæde", ["counterfactual-chain", "årsag"], "Hvert led skal føre til det næste uden at blive til fakta.", "Kæden holder alarm, reaktion og begrænsning i samme uvirkelige fortidsverden.", "produce"), premises: ["Alarmen virkede ikke.", "Vagten reagerede ikke.", "Branden spredte sig."], tokens: ["Hvis alarmen havde virket,", "havde vagten reageret,", "og branden var blevet begrænset."], acceptedAnswers: ["Hvis alarmen havde virket, havde vagten reageret, og branden var blevet begrænset."] }),
      buildChoice({ ...common("l19-m01-q06", "Hvad ved vi sikkert fra: “Hvis hun havde ringet, var vi blevet hjemme” ?", "Hun ringede ikke, og vi blev ikke hjemme.", "She did not call, and we did not stay home.", "irrealis", ["implikatur", "fortid"], "Kontrafaktisk form inviterer en slutning om virkeligheden.", "Begge led fremstilles som modsætninger til det, der faktisk skete."), options: ["Hun ringede, og vi blev hjemme.", "Hun ringede ikke, og vi blev ikke hjemme.", "Vi ved kun, at telefonen var ny."] }),
      buildTransform({ ...common("l19-m01-q07", "Gør beklagelsen grammatisk tydelig.", "Hvis jeg havde lyttet til dig, havde vi undgået fejlen.", "If I had listened to you, we would have avoided the error.", "irrealis", ["transform", "beklagelse"], "Gør både det manglende valg og den tabte følge synlige.", "Kontrafaktisk førdatid forbinder ansvar med et alternativ uden at omskrive historien.", "produce"), sourceSentence: "Jeg lyttede ikke. Vi begik fejlen.", instruction: "Saml med hvis og uvirkelig fortid.", acceptedAnswers: ["Hvis jeg havde lyttet til dig, havde vi undgået fejlen."] }),
      buildExplainWhy({ ...common("l19-m01-q08", "Forklar, hvad en kontrafaktisk sætning påstår, og hvad den kun forestiller sig.", "AI-bedømt forklaring", "Explain what a counterfactual sentence asserts and what it only imagines.", "irrealis", ["explain-why", "semantik"], "Adskil den virkelige tidslinje fra alternativet.", "Svaret vurderes på faktuel implikation, den uvirkelige betingelse og den forestillede konsekvens.", "produce"), claim: "Hvis vagten havde set røgen, havde hun slået alarm.", requiredConcepts: ["vagten så ikke røgen", "alarmen blev ikke slået på dette grundlag", "alternativ årsagskæde"], minWords: 50, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["virkelig tidslinje", "uopfyldt betingelse", "forestillet følge"] } }),
    ]),
    mission("l19-m02", "Kunne, skulle, burde", "Modal perfektum og graden af ansvar", "compass", [
      buildChoice({ ...common("l19-m02-q01", "Vælg den bedste kritik: Teknikeren havde pligt til at teste alarmen, men gjorde det ikke.", "Teknikeren skulle have testet alarmen.", "The technician was supposed to have tested the alarm.", "modal perfektum", ["skulle-have", "pligt"], "Der var en konkret forventning eller pligt.", "Skulle have markerer en uopfyldt plan eller forpligtelse."), options: ["Teknikeren kunne have testet alarmen.", "Teknikeren skulle have testet alarmen.", "Teknikeren ville have testet alarmen."] }),
      buildChoice({ ...common("l19-m02-q02", "Vælg den rimelige efterkritik: Lederen valgte en farlig genvej trods advarsler.", "Lederen burde have fulgt proceduren.", "The manager should have followed the procedure.", "modal perfektum", ["burde-have", "vurdering"], "Sætningen er en normativ vurdering, ikke en teknisk mulighed.", "Burde have udtrykker den talendes vurdering af et bedre fortidigt valg."), options: ["Lederen burde have fulgt proceduren.", "Lederen kunne flyve proceduren.", "Lederen vil have proceduren."] }),
      buildErrorHunt({ ...common("l19-m02-q03", "Find modalverbet, der anklager i stedet for blot at beskrive mulighed.", "kunne", "They could have noticed the error, but the screen was dark.", "modal perfektum", ["error-hunt", "kunne-have"], "Skærmen var en reel begrænsning; pligt er ikke oplyst.", "Kunne have holder udsagnet på mulighedsniveau; burde have ville tilføje en moralsk dom.", "produce"), sentenceTokens: ["De", "burde", "have", "set", "fejlen,", "men", "skærmen", "var", "sort."], errorIndex: 1, correction: "kunne" }),
      buildOrder({ ...common("l19-m02-q04", "Byg den præcise ansvarsfordeling.", "Vagten kunne have reageret, men lederen skulle have vedligeholdt alarmen.", "The guard could have reacted, but the manager was supposed to maintain the alarm.", "modal perfektum", ["kunne-have", "skulle-have"], "Skeln mellem mulighed og formel pligt.", "Kunne have beskriver vagtens mulighed; skulle have placerer den uopfyldte forpligtelse hos lederen.", "produce"), tokens: ["Vagten kunne have reageret,", "men lederen", "skulle have vedligeholdt", "alarmen."], acceptedAnswers: ["Vagten kunne have reageret, men lederen skulle have vedligeholdt alarmen."] }),
      buildInput({ ...common("l19-m02-q05", "Udfyld den varme beklagelse: Jeg ___ have ringet, da du stod alene.", "burde", "I should have called when you were alone.", "modal perfektum", ["burde-have", "omsorg"], "Taleren vurderer sit eget valg bagefter.", "Burde have kan udtrykke ansvar uden at angribe modtageren.", "produce"), acceptedAnswers: ["burde", "Burde"] }),
      buildCounterfactualChain({ ...common("l19-m02-q06", "Byg kæden med mulighed, pligt og forventet resultat.", "Maja kunne have stoppet maskinen, fordi hun skulle have overvåget trykket; så ville skaden være undgået.", "Maja could have stopped the machine because she was supposed to monitor the pressure; then the damage would have been avoided.", "kontrafaktisk kæde", ["counterfactual-chain", "modalitet"], "Lad modalverberne gøre forskelligt arbejde.", "Kunne have markerer mulighed, skulle have pligt og ville have den forventede alternative følge.", "produce"), premises: ["Maja havde adgang til stopknappen.", "Hun havde pligt til at overvåge trykket.", "Skaden skete."], tokens: ["Maja kunne have stoppet maskinen,", "fordi hun skulle have overvåget trykket;", "så ville skaden være undgået."], acceptedAnswers: ["Maja kunne have stoppet maskinen, fordi hun skulle have overvåget trykket; så ville skaden være undgået."] }),
      buildChoice({ ...common("l19-m02-q07", "Hvilken sætning er mest aggressiv?", "Du burde have vidst bedre.", "You should have known better.", "modal perfektum", ["tone", "burde-have"], "Modal perfektum kan bære social dom, ikke kun grammatik.", "Du burde have vidst bedre angriber modtagerens dømmekraft og forudsatte ansvar."), options: ["Det kunne måske have været tydeligere.", "Du burde have vidst bedre.", "Vi kunne have valgt en anden løsning."] }),
      buildMicroDialogue({ ...common("l19-m02-q08", "Tal med en stædig sikkerhedschef efter en næsten-ulykke.", "AI-bedømt dialog", "Speak with a stubborn safety manager after a near miss.", "ansvarssamtale", ["micro-dialogue", "modal-perfektum"], "Få en konkret ændring uden at opgive forskellen mellem kunne, skulle og burde.", "Dialogen vurderes på præcis ansvarsplacering, deeskalering og en verificerbar aftale.", "produce"), persona: "En defensiv sikkerhedschef, der afviser moralske foredrag, men reagerer på konkrete procedurer.", hiddenGoal: "Få chefen til at love en dokumenteret ugentlig alarmtest uden at acceptere falsk individuelt ansvar.", turns: 3, minWords: 36, aiPolicy: { mode: "grade", task: "micro-dialogue", skipWhenUnavailable: true, persona: "defensiv sikkerhedschef", hiddenGoal: "opnå dokumenteret ugentlig alarmtest" } }),
    ], 880),
    mission("l19-m03", "Dominoer baglæns", "Lange kontrafaktiske årsagskæder", "layers", [
      buildCounterfactualChain({ ...common("l19-m03-q01", "Byg den tekniske kæde.", "Hvis sensoren havde målt korrekt, var pumpen stoppet, og tanken var ikke løbet over.", "If the sensor had measured correctly, the pump would have stopped and the tank would not have overflowed.", "kontrafaktisk kæde", ["counterfactual-chain", "teknik"], "Forbind fejlmåling, styring og fysisk følge.", "Alle tre led holdes som et alternativ til det dokumenterede overløb.", "produce"), premises: ["Sensoren målte forkert.", "Pumpen fortsatte.", "Tanken løb over."], tokens: ["Hvis sensoren havde målt korrekt,", "var pumpen stoppet,", "og tanken var ikke løbet over."], acceptedAnswers: ["Hvis sensoren havde målt korrekt, var pumpen stoppet, og tanken var ikke løbet over."] }),
      buildCounterfactualChain({ ...common("l19-m03-q02", "Byg den menneskelige kæde uden at gøre den mekanisk.", "Hvis Jonas havde sagt sandheden, havde Lea stolet på ham, og samarbejdet var måske fortsat.", "If Jonas had told the truth, Lea would have trusted him, and the collaboration might have continued.", "kontrafaktisk kæde", ["counterfactual-chain", "relation"], "Den sidste følge er mulig, ikke sikker.", "Måske begrænser den sociale forudsigelse, som ikke kan bevises mekanisk.", "produce"), premises: ["Jonas løj.", "Lea mistede tilliden.", "Samarbejdet sluttede."], tokens: ["Hvis Jonas havde sagt sandheden,", "havde Lea stolet på ham,", "og samarbejdet var måske fortsat."], acceptedAnswers: ["Hvis Jonas havde sagt sandheden, havde Lea stolet på ham, og samarbejdet var måske fortsat."] }),
      buildChoice({ ...common("l19-m03-q03", "Hvilket led er for sikkert i kæden?", "så var virksomheden helt sikkert blevet markedsleder", "then the company would certainly have become market leader", "kontrafaktisk kæde", ["sikkerhedsgrad", "kausalitet"], "En reparation kan påvirke salg, men garanterer ikke hele markedet.", "Helt sikkert overdriver forbindelsen mellem en lokal teknisk ændring og et komplekst markedsresultat."), options: ["hvis fejlen var blevet rettet", "var produktionen måske steget", "så var virksomheden helt sikkert blevet markedsleder"] }),
      buildErrorHunt({ ...common("l19-m03-q04", "Find markøren, der gør en usikker social følge til en fysisk lov.", "måske", "If she had apologised, the conflict might have ended.", "kontrafaktisk kæde", ["error-hunt", "hedging"], "Mennesker reagerer ikke deterministisk.", "Måske kalibrerer den forestillede følge; nødvendigvis er uberettiget.", "produce"), sentenceTokens: ["Hvis", "hun", "havde", "undskyldt,", "var", "konflikten", "nødvendigvis", "sluttet."], errorIndex: 6, correction: "måske" }),
      buildTextOrder({ ...common("l19-m03-q05", "Ordne haverirapportens faktiske og alternative tidslinjer.", "a>b>c>d>e>f", "Order the actual and alternative timelines in the accident report.", "tekstsammenhæng", ["text-order", "kontrafaktisk"], "Etabler først fakta, og markér derefter tydeligt skiftet til alternativet.", "Teksten går fra hændelser til analyse og undgår at blande forestillede resultater ind som fakta.", "produce"), sentences: [{ id: "a", text: "Ventilen satte sig fast klokken 9.12." }, { id: "b", text: "Operatøren så først alarmen fire minutter senere." }, { id: "c", text: "Trykket beskadigede derfor røret." }, { id: "d", text: "En tidligere alarm kunne have ændret forløbet." }, { id: "e", text: "Hvis signalet var kommet klokken 9.12, havde operatøren kunnet stoppe pumpen." }, { id: "f", text: "Det beviser dog ikke, at enhver skade var blevet undgået." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["e", "c", "a", "f", "b", "d"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildOrder({ ...common("l19-m03-q06", "Byg den kalibrerede konklusion.", "Fejlen var nødvendig for forløbet, men måske ikke tilstrækkelig til hele skaden.", "The error was necessary to the sequence, but perhaps not sufficient for all the damage.", "kausalitet", ["nødvendig", "tilstrækkelig"], "Skeln mellem at muliggøre en kæde og at forklare alt.", "Sætningen begrænser årsagspåstanden med nødvendighed, tilstrækkelighed og måske.", "produce"), tokens: ["Fejlen var nødvendig", "for forløbet,", "men måske ikke tilstrækkelig", "til hele skaden."], acceptedAnswers: ["Fejlen var nødvendig for forløbet, men måske ikke tilstrækkelig til hele skaden."] }),
      buildChoice({ ...common("l19-m03-q07", "Hvilken slutning er logisk gyldig?", "Hvis A var forhindret, var denne kæde ikke sket på samme måde.", "If A had been prevented, this chain would not have happened in the same way.", "kausalitet", ["kontrafaktisk-test", "logik"], "Påstå kun noget om den beskrevne kæde.", "Den kontrafaktiske test støtter betydning for netop forløbet, ikke at A er universel eneårsag."), options: ["A er årsag til alle lignende skader.", "Hvis A var forhindret, var denne kæde ikke sket på samme måde.", "A beviser, at ingen andre faktorer fandtes."] }),
      buildCompress({ ...common("l19-m03-q08", "Komprimer analysen til højst 32 danske ord uden at gøre en mulighed til sikkerhed.", "AI-bedømt komprimering", "Compress the analysis to no more than 32 Danish words without turning possibility into certainty.", "kontrafaktisk analyse", ["compress", "hedging"], "Bevar både den stærke tekniske forbindelse og den svage organisatoriske følge.", "Svaret vurderes på årsagskæde, forskellig sikkerhedsgrad og ordgrænsen.", "produce"), sourceText: "Hvis kølingen havde virket, var temperaturen sandsynligvis faldet, og maskinen var næppe stoppet. Produktionen kunne derefter være fortsat, men kundens ordre var måske stadig blevet forsinket af strejken.", maxWords: 32, requiredFacts: ["køling kunne sænke temperatur", "maskinstop næppe", "produktion muligvis fortsat", "strejke kunne stadig forsinke"], minWords: 20, aiPolicy: { mode: "grade", task: "compress", skipWhenUnavailable: true, maxWords: 32, requiredFacts: ["køling og temperatur", "maskinstop", "produktion", "strejkerisiko"] } }),
    ], 900),
    mission("l19-m04", "Efter dommen", "Ansvar, nåde og alternative valg", "star", [
      buildChoice({ ...common("l19-m04-q01", "Hvilken formulering undersøger ansvar uden bagklog arrogance?", "Hvad kunne de med rimelighed have vidst på beslutningstidspunktet?", "What could they reasonably have known at the time of the decision?", "ansvar", ["modal-perfektum", "rimelighed"], "Vurder fortiden med de oplysninger, der faktisk fandtes.", "Spørgsmålet begrænser bagklogskab ved at forankre mulighed i beslutningstidspunktet."), options: ["Hvordan kunne de være så dumme?", "Hvad kunne de med rimelighed have vidst på beslutningstidspunktet?", "Hvorfor forudså de ikke alt?"] }),
      buildCounterfactualChain({ ...common("l19-m04-q02", "Byg den proportionelle ansvarsanalyse.", "Hvis lederen havde læst advarslen, burde hun have standset testen; men hun kunne ikke have forudset den skjulte fabrikationsfejl.", "If the manager had read the warning, she should have stopped the test; but she could not have foreseen the hidden manufacturing defect.", "ansvar", ["counterfactual-chain", "proportionalitet"], "Del den kendelige risiko fra den skjulte fejl.", "Kæden placerer ansvar for den ignorerede advarsel uden at opfinde ansvar for det ukendelige.", "produce"), premises: ["Advarslen var tilgængelig.", "Den blev ikke læst.", "En anden fejl var skjult."], tokens: ["Hvis lederen havde læst advarslen,", "burde hun have standset testen;", "men hun kunne ikke have forudset den skjulte fabrikationsfejl."], acceptedAnswers: ["Hvis lederen havde læst advarslen, burde hun have standset testen; men hun kunne ikke have forudset den skjulte fabrikationsfejl."] }),
      buildErrorHunt({ ...common("l19-m04-q03", "Find modalverbet, der gør tilgivelse til frifindelse.", "kunne", "He could not have known about the sealed report.", "ansvar", ["error-hunt", "kunne-ikke-have"], "Rapporten var reelt utilgængelig.", "Kunne ikke have kendt markerer manglende mulighed; burde ikke have kendt giver ingen mening her.", "produce"), sentenceTokens: ["Han", "burde", "ikke", "have", "kendt", "den", "forseglede", "rapport."], errorIndex: 1, correction: "kunne" }),
      buildOrder({ ...common("l19-m04-q04", "Byg den noble erkendelse.", "Jeg kunne have forsvaret mig, men jeg burde have lyttet først.", "I could have defended myself, but I should have listened first.", "ansvar", ["kunne-have", "burde-have", "varme"], "Mulighed er ikke det samme som det bedste valg.", "Kontrasten accepterer handlemuligheden, men prioriterer et mere omsorgsfuldt ansvar.", "produce"), tokens: ["Jeg kunne have", "forsvaret mig,", "men jeg burde have", "lyttet først."], acceptedAnswers: ["Jeg kunne have forsvaret mig, men jeg burde have lyttet først."] }),
      buildInput({ ...common("l19-m04-q05", "Udfyld: Vi ___ have fordelt risikoen, før én person bar hele presset.", "burde", "We should have distributed the risk before one person carried all the pressure.", "ansvar", ["burde-have", "fællesskab"], "Sætningen vurderer organisationens valg.", "Burde have udtrykker en kollektiv normativ beklagelse.", "produce"), acceptedAnswers: ["burde", "Burde"] }),
      buildTextOrder({ ...common("l19-m04-q06", "Ordne efteranalysen fra fakta til læring.", "a>b>c>d>e", "Order the post-incident analysis from facts to learning.", "tekstsammenhæng", ["text-order", "ansvar"], "Læring kommer efter dokumentation og kontrafaktisk test.", "Rækkefølgen modvirker syndebukke ved først at etablere data og først til sidst ændre praksis.", "produce"), sentences: [{ id: "a", text: "Først fastlægges den faktiske tidslinje." }, { id: "b", text: "Derefter vurderes, hvilke oplysninger hver aktør havde." }, { id: "c", text: "Mulige alternative valg testes mod de samme data." }, { id: "d", text: "Ansvar placeres kun, hvor handling og viden mødtes." }, { id: "e", text: "Til sidst ændres systemet, så fejlen bliver sværere at gentage." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["c", "a", "e", "b", "d"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildChoice({ ...common("l19-m04-q07", "Hvilken sætning er hård uden at være doven?", "Du burde have læst loggen; den røde advarsel stod på første side.", "You should have read the log; the red warning was on the first page.", "ansvar", ["kritik", "evidens"], "En stærk dom bør bære sit bevis med sig.", "Kritikken forbinder pligt med en konkret, tilgængelig advarsel."), options: ["Du er bare håbløs.", "Du burde have læst loggen; den røde advarsel stod på første side.", "Alt er alles skyld."] }),
      buildExplainWhy({ ...common("l19-m04-q08", "Forklar forskellen mellem at forstå et valg og at undskylde det.", "AI-bedømt forklaring", "Explain the difference between understanding a choice and excusing it.", "ansvar", ["explain-why", "etik", "kontrafaktisk"], "Brug viden, handlemuligheder og konsekvenser som tre separate akser.", "Svaret vurderes på empatisk forklaring, bevaret ansvar og en kontrafaktisk forbedring.", "produce"), claim: "Kontekst kan mindske eller omfordele ansvar uden at gøre skaden uvirkelig.", requiredConcepts: ["viden på tidspunktet", "reelle alternativer", "proportionalt ansvar", "læring"], minWords: 65, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["forklaring er ikke frifindelse", "ansvar afhænger af viden og mulighed", "alternativet skal være realistisk"] } }),
    ], 920),
  ],
};
