import {
  buildChoice, buildErrorHunt, buildFreeRewrite, buildInflectionForge, buildInput,
  buildNuanceScale, buildOrder, buildTextOrder, buildTransform,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";
import { buildInflectionForge as lexicalInflection, buildNuanceScale as lexicalNuance } from "../../lexicalBanks.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 2): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 650) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });

const comparison = lexicalInflection("inf-god-comparative");
const certainty = lexicalNuance("scale-certainty");

export const level15: CourseLevel = {
  id: "level-15", eyebrow: "A2+ · Niveau 15", title: "Retning og rum",
  description: "Bevæg dig præcist gennem rum, retning og sammenligninger — også når kortet er tegnet af en optimist.",
  color: "#e16f52", unlockXp: 14500,
  missions: [
    mission("l15-m01", "Ud eller ude?", "Retning er en bevægelse; sted er et resultat", "map", [
      buildChoice({ ...common("l15-m01-q01", "Vælg: Katten løber ___ gennem døren.", "ud", "The cat runs out through the door.", "retningsadverbier", ["ud-ude", "bevægelse"], "Er der bevægelse mod en grænse?", "Ud beskriver bevægelsen fra et indre rum mod ydersiden."), options: ["ud", "ude", "ind", "inde"] }),
      buildChoice({ ...common("l15-m01-q02", "Vælg: Katten sidder allerede ___ i regnen og fortryder alt.", "ude", "The cat is already sitting outside in the rain and regrets everything.", "retningsadverbier", ["ud-ude", "sted"], "Handlingen har nået sit sted.", "Ude beskriver en statisk placering, ikke en retning."), options: ["ud", "ude", "op", "oppe"] }),
      buildOrder({ ...common("l15-m01-q03", "Byg beskeden til flyttefolkene.", "Bær kassen ind, og stil den inde i depotet.", "Carry the box inside, and place it inside the storage room.", "retningsadverbier", ["ind-inde", "imperativ"], "Først bevægelse, derefter placering.", "Ind følger bevægelsesverbet bær; inde lokaliserer kassen efter bevægelsen.", "produce"), tokens: ["Bær kassen", "ind,", "og stil den", "inde i depotet."], acceptedAnswers: ["Bær kassen ind, og stil den inde i depotet."] }),
      buildErrorHunt({ ...common("l15-m01-q04", "Find retningsfejlen, og ret den.", "ind", "Go inside and wait inside the foyer.", "retningsadverbier", ["error-hunt", "ind-inde"], "Klik på det ord, der beskriver bevægelsen forkert.", "Efter gå skal retningen være ind; inde passer først efter vent.", "produce"), sentenceTokens: ["Gå", "inde", "og", "vent", "inde", "i", "foyeren."], errorIndex: 1, correction: "ind" }),
      buildChoice({ ...common("l15-m01-q05", "Vælg: Elevatorens dør går ___, men vi står stadig ___ på gaden.", "op | nede", "The lift goes up, but we are still down on the street.", "retningsadverbier", ["op-oppe", "kontrast"], "Skeln mellem elevatorens retning og vores sted.", "Op angiver bevægelse; nede angiver den fortsatte placering."), options: ["op | nede", "oppe | ned", "oppe | nede"] }),
      buildInput({ ...common("l15-m01-q06", "Udfyld stedet: Når du er kommet op, venter jeg ___ ved klokken.", "oppe", "Once you have come up, I will wait upstairs by the bell.", "retningsadverbier", ["op-oppe", "sted"], "Venter beskriver placering.", "Oppe er stedsformen efter den afsluttede bevægelse.", "produce"), acceptedAnswers: ["oppe", "Oppe"] }),
      buildTransform({ ...common("l15-m01-q07", "Gør den uklare besked rumligt præcis.", "Gå hen til skranken, og vent henne ved den blå lampe.", "Go over to the counter and wait over there by the blue lamp.", "retningsadverbier", ["hen-henne", "transform"], "Brug én form for bevægelsen og én for stedet.", "Hen angiver målet for gå; henne fastholder stedet for vent.", "produce", 3), sourceSentence: "Gå til skranken og vent ved lampen.", instruction: "Brug både hen og henne.", acceptedAnswers: ["Gå hen til skranken, og vent henne ved den blå lampe."] }),
      buildFreeRewrite({ ...common("l15-m01-q08", "Skriv en præcis rute gennem bygningen på dansk.", "AI-bedømt rute", "Write a precise route through the building in Danish.", "retningsadverbier", ["free-rewrite", "ud-ude", "ind-inde"], "Brug mindst tre par som ind/inde eller op/oppe.", "Svaret vurderes for korrekt skelnen mellem retning og placering.", "produce", 3), sourceText: "Start outside, enter, go upstairs, cross the hall, and wait by the red door.", instruction: "Omskriv ruten naturligt med mindst tre retnings-/stedspar.", minWords: 24, aiPolicy: { mode: "grade", task: "free-rewrite", skipWhenUnavailable: true, requiredFacts: ["starter ude", "går ind", "går op", "venter ved den røde dør"] } }),
    ]),
    mission("l15-m02", "Kortet lyver ikke", "Rumlige relationer, landmærker og sammenhæng", "compass", [
      buildChoice({ ...common("l15-m02-q01", "Vælg den præcise vej: Apoteket ligger ___ banken og bageriet.", "mellem", "The pharmacy is between the bank and the bakery.", "rumlige præpositioner", ["mellem", "landmærker"], "Der er ét sted på hver side.", "Mellem forbinder placeringen med to referencepunkter."), options: ["mellem", "gennem", "hen over", "forbi"] }),
      buildOrder({ ...common("l15-m02-q02", "Byg ruten uden at teleportere.", "Gå forbi kirken, hen over broen og ind i gården.", "Walk past the church, across the bridge, and into the courtyard.", "ruteinstruktion", ["forbi", "hen-over", "ind"], "Følg landmærkerne i den rækkefølge, de mødes.", "Ruten bevæger sig forbi et punkt, over en flade og til sidst ind i et rum.", "produce"), tokens: ["Gå forbi kirken,", "hen over broen", "og ind i gården."], acceptedAnswers: ["Gå forbi kirken, hen over broen og ind i gården."] }),
      buildChoice({ ...common("l15-m02-q03", "Hvad betyder “lige over for stationen” ?", "på den modsatte side med stationen som reference", "on the opposite side, facing the station", "rumlige præpositioner", ["over-for", "sted"], "Det handler ikke om højde.", "Lige over for angiver en placering på den modsatte side."), options: ["på den modsatte side med stationen som reference", "direkte oven på stationen", "langt bag stationen"] }),
      buildErrorHunt({ ...common("l15-m02-q04", "Find ordet, der sender turisten den forkerte vej.", "forbi", "Walk past the museum and turn left at the harbour.", "ruteinstruktion", ["error-hunt", "forbi"], "Museet skal passeres, ikke gennemtrænges.", "Forbi betyder at passere et landmærke; gennem ville føre ruten ind i museet.", "produce"), sentenceTokens: ["Gå", "gennem", "museet", "og", "drej", "til", "venstre", "ved", "havnen."], errorIndex: 1, correction: "forbi" }),
      buildTextOrder({ ...common("l15-m02-q05", "Sæt de fem ruteinstruktioner i en mulig, sammenhængende rækkefølge.", "a>b>c>d>e", "Put the five route instructions in a coherent order.", "tekstsammenhæng", ["text-order", "rute"], "Begynd ved udgangen, og lad hvert nyt sted blive næste udgangspunkt.", "Sekvensen kæder udgangen, pladsen, broen, tårnet og gården fysisk sammen.", "produce", 3), sentences: [{ id: "a", text: "Gå ud gennem hoveddøren." }, { id: "b", text: "Kryds derefter pladsen." }, { id: "c", text: "Fortsæt hen over den lave bro." }, { id: "d", text: "Drej til højre ved tårnet." }, { id: "e", text: "Vent til sidst inde i gården." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["c", "a", "e", "b", "d"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildInput({ ...common("l15-m02-q06", "Udfyld: Cykelstien løber ___ kanalen hele vejen til slusen.", "langs", "The cycle path runs along the canal all the way to the lock.", "rumlige præpositioner", ["langs", "rute"], "Ruten følger den samme linje som kanalen.", "Langs beskriver en parallel bevægelse ved siden af noget.", "produce"), acceptedAnswers: ["langs", "Langs"] }),
      buildChoice({ ...common("l15-m02-q07", "Hvilken instruktion er farligt upræcis på en travl kaj?", "Gå derhen og stil den der.", "Go over there and put it there.", "referencer", ["deiksis", "præcision"], "Find sætningen uden stabile landmærker.", "Derhen og der afhænger af et synligt fælles perspektiv, som modtageren måske ikke deler."), options: ["Gå derhen og stil den der.", "Gå hen til kranen og stil kassen under skiltet.", "Følg den gule linje ind i lageret."] }),
      buildTransform({ ...common("l15-m02-q08", "Erstat de vage stedord med brugbare landmærker.", "Gå hen til den grønne port, og vent henne ved vagtboden.", "Go to the green gate and wait by the guard booth.", "referencer", ["transform", "hen-henne"], "Den reviderede rute skal kunne følges uden en pegende hånd.", "Konkrete landmærker gør både bevægelsens mål og ventestedet entydige.", "produce", 3), sourceSentence: "Gå derhen, og vent der.", instruction: "Brug hen/henne og to konkrete landmærker.", acceptedAnswers: ["Gå hen til den grønne port, og vent henne ved vagtboden."] }),
    ], 670),
    mission("l15-m03", "Mål uden pral", "Komparativ, lighed og nøgterne sammenligninger", "layers", [
      buildInflectionForge({ ...common("l15-m03-q01", `${comparison.promptDa} ${comparison.contextDa}`, comparison.answerDa, "Form the comparative of good.", "komparation", ["inflection-forge", "bedre"], "God bøjes uregelmæssigt.", "Komparativ af god er bedre, ikke mere god.", "produce"), lemma: "god", targetDescription: "komparativ", acceptedAnswers: [...comparison.acceptableAnswersDa] }),
      buildChoice({ ...common("l15-m03-q02", "Vælg: Den nye færge er ___ end den gamle.", "hurtigere", "The new ferry is faster than the old one.", "komparation", ["-ere", "end"], "Sammenlign to færger.", "Komparativ dannes her med -ere og følges af end."), options: ["hurtig", "hurtigere", "hurtigst", "lige hurtig"] }),
      buildOrder({ ...common("l15-m03-q03", "Byg en lighed uden at gøre nogen til vinder.", "Den lille motor er lige så stabil som den store.", "The small engine is just as stable as the large one.", "komparation", ["lige-så-som", "lighed"], "Lighed rammes ind af lige så og som.", "Lige så ... som udtrykker samme grad mellem to størrelser.", "produce"), tokens: ["Den lille motor", "er lige så stabil", "som den store."], acceptedAnswers: ["Den lille motor er lige så stabil som den store."] }),
      buildChoice({ ...common("l15-m03-q04", "Hvilken påstand er mest nøgtern, når målingen kun viser 2 % forskel?", "Model B er en smule mere effektiv end model A.", "Model B is slightly more efficient than model A.", "komparation", ["grad", "præcision"], "Lad sprogets styrke svare til tallets størrelse.", "En smule markerer en lille, målbar forskel uden overdrivelse."), options: ["Model B knuser model A.", "Model B er en smule mere effektiv end model A.", "Model B er uendeligt bedre."] }),
      buildNuanceScale({ ...common("l15-m03-q05", certainty.promptDa, certainty.orderedAnswerDa.join(" < "), "Order the expressions from least to greatest certainty.", "nuance", ["nuance-scale", "sikkerhed"], "Begynd med den mest åbne tvivl.", "Rækkefølgen følger bankens graderede sikkerhedsskala.", "produce", 3), axis: "sikkerhed", tokens: [...certainty.termsDa].reverse(), acceptedAnswers: [certainty.orderedAnswerDa.join(" < ")] }),
      buildErrorHunt({ ...common("l15-m03-q06", "Find fejlen i sammenligningen.", "som", "The harbour is as busy as yesterday.", "komparation", ["error-hunt", "lige-så-som"], "Lige så kræver en bestemt afslutning.", "Lighedskonstruktionen hedder lige så travl som, ikke end.", "produce"), sentenceTokens: ["Havnen", "er", "lige", "så", "travl", "end", "i", "går."], errorIndex: 5, correction: "som" }),
      buildInput({ ...common("l15-m03-q07", "Udfyld korrelativet: Jo længere vi venter, ___ dyrere bliver reparationen.", "desto", "The longer we wait, the more expensive the repair becomes.", "korrelativ-komparation", ["jo-desto", "sammenhæng"], "Første led begynder med jo.", "Jo ... desto kobler to gradvise forandringer.", "produce", 3), acceptedAnswers: ["desto", "Desto"] }),
      buildTransform({ ...common("l15-m03-q08", "Gør de to observationer til én gradvis sammenhæng.", "Jo højere vandet stiger, desto langsommere kører trafikken.", "The higher the water rises, the slower the traffic moves.", "korrelativ-komparation", ["transform", "jo-desto"], "Begge led skal stå i komparativ.", "Jo ... desto udtrykker, at to målbare ændringer udvikler sig sammen.", "produce", 3), sourceSentence: "Vandet stiger. Trafikken kører langsommere.", instruction: "Saml med jo ... desto.", acceptedAnswers: ["Jo højere vandet stiger, desto langsommere kører trafikken."] }),
    ], 680),
    mission("l15-m04", "Rummet under pres", "Lange instruktioner, relative mål og konsekvenser", "target", [
      buildChoice({ ...common("l15-m04-q01", "Vælg den eneste sikre placering: Nødudgangen skal være ___ for paller.", "fri", "The emergency exit must be clear of pallets.", "rumlig sikkerhed", ["sted", "sikkerhed"], "Ingen genstand må blokere passagen.", "Fri for betyder, at området ikke indeholder den nævnte hindring."), options: ["fri", "forbi", "henne", "imellem"] }),
      buildOrder({ ...common("l15-m04-q02", "Byg den strenge inspektionstekst.", "Flyt tønderne væk fra døren, før vagten kommer ind.", "Move the barrels away from the door before the guard comes in.", "ruteinstruktion", ["væk-fra", "før"], "Hindringen skal flyttes før inspektionen.", "Væk fra angiver retningen, og før-leddet fastlægger rækkefølgen.", "produce"), tokens: ["Flyt tønderne", "væk fra døren,", "før vagten", "kommer ind."], acceptedAnswers: ["Flyt tønderne væk fra døren, før vagten kommer ind."] }),
      buildChoice({ ...common("l15-m04-q03", "Hvor står reservedelene, hvis de er “oven på skabet” ?", "på skabets øverste flade", "on the top surface of the cabinet", "rumlige relationer", ["oven-på", "sted"], "Skel mellem ovenpå og oven for.", "Oven på tager et objekt og angiver fysisk kontakt med dets øverste flade."), options: ["på skabets øverste flade", "højere end skabet uden kontakt", "inde i skabet"] }),
      buildErrorHunt({ ...common("l15-m04-q04", "Find ordet, der gør sikkerhedsbeskeden selvmodsigende.", "væk", "Move away from the edge and stay inside the marked field.", "rumlig sikkerhed", ["error-hunt", "væk"], "Retningen skal øge afstanden til kanten.", "Væk fra kanten er sikker; hen mod kanten ville mindske afstanden.", "produce"), sentenceTokens: ["Gå", "hen", "mod", "kanten", "og", "bliv", "inde", "i", "feltet."], errorIndex: 1, correction: "væk" }),
      buildTextOrder({ ...common("l15-m04-q05", "Ordne evakueringsbeskeden, så ingen sendes tilbage mod røgen.", "a>b>c>d>e>f", "Order the evacuation instructions safely.", "tekstsammenhæng", ["text-order", "evakuering"], "Placér alarmen før bevægelsen og samlingsstedet til sidst.", "Den logiske rækkefølge går fra alarm og orientering til udgang, afstand og optælling.", "produce", 3), sentences: [{ id: "a", text: "Når alarmen lyder, skal du stoppe arbejdet." }, { id: "b", text: "Se efter det grønne udgangsskilt." }, { id: "c", text: "Gå ud gennem den nærmeste sikre dør." }, { id: "d", text: "Fortsæt væk fra bygningen." }, { id: "e", text: "Stil dig henne ved flagstangen." }, { id: "f", text: "Meld dig til den ansvarlige." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["d", "b", "f", "a", "e", "c"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildChoice({ ...common("l15-m04-q06", "Hvilken formulering er både præcis og menneskelig?", "Gå roligt ud, og hjælp den person, der står nærmest dig.", "Walk out calmly and help the person nearest to you.", "instruktionsregister", ["varme", "præcision"], "En god instruktion kan være klar uden at være kold.", "Sætningen forener handlingsretning, tempo og konkret omsorg."), options: ["FORLAD ARENAEN, TABERE!", "Gå roligt ud, og hjælp den person, der står nærmest dig.", "Der bør eventuelt ske en bevægelse."] }),
      buildInput({ ...common("l15-m04-q07", "Udfyld: Jo tættere røgen kommer på, ___ vigtigere bliver det at holde sig nede.", "desto", "The closer the smoke gets, the more important it becomes to stay low.", "korrelativ-komparation", ["jo-desto", "sikkerhed"], "Kobl de to stigende grader.", "Desto indleder konsekvensleddet i korrelationen.", "produce", 3), acceptedAnswers: ["desto", "Desto"] }),
      buildTransform({ ...common("l15-m04-q08", "Omskriv skiltet til en konkret rute.", "Gå ud gennem den blå dør, ned ad trappen og hen til pladsen.", "Go out through the blue door, down the stairs, and over to the square.", "ruteinstruktion", ["transform", "ud-ned-hen"], "Navngiv tre bevægelser og deres mål.", "Ruten bruger konsekvente retningsformer og stabile landmærker.", "produce", 3), sourceSentence: "Evakuér korrekt.", instruction: "Skriv en rute med ud, ned og hen.", acceptedAnswers: ["Gå ud gennem den blå dør, ned ad trappen og hen til pladsen."] }),
    ], 700),
  ],
};
