import {
  buildChoice, buildCompress, buildErrorHunt, buildEvidentialTag, buildExplainWhy,
  buildFreeRewrite, buildMicroDialogue, buildNuanceScale, buildOrder, buildSynonymPick,
  buildTextOrder, buildTransform,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";
import { buildNuanceScale as lexicalNuance, buildSynonymPick as lexicalSynonym } from "../../lexicalBanks.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 3): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 920) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });
const criticism = lexicalNuance("scale-criticism");
const showEvidence = lexicalSynonym("syn-show-evidence");
const tentativeThink = lexicalSynonym("syn-think-tentative");

export const level20: CourseLevel = {
  id: "level-20", eyebrow: "B2 · Niveau 20", title: "Den sidste formulering",
  description: "Saml nuance, fokus, partikler og argumentation til dansk, der kan bære vægten af en virkelig beslutning.",
  color: "#c05e78", unlockXp: 29000,
  missions: [
    mission("l20-m01", "Et ords vægt", "Nuance, intensitet og kontrolleret skarphed", "sparkles", [
      buildNuanceScale({ ...common("l20-m01-q01", criticism.promptDa, criticism.orderedAnswerDa.join(" < "), "Order the criticism from mildest to strongest.", "nuance", ["nuance-scale", "kritik"], "Begynd med den formulering, der åbner mest for revision.", "Bankens skala ordner kritikken efter styrke, ikke efter hvor høflig skrifttypen ser ud.", "produce"), axis: "kritikkens styrke", tokens: [...criticism.termsDa].reverse(), acceptedAnswers: [criticism.orderedAnswerDa.join(" < ")] }),
      buildSynonymPick({ ...common("l20-m01-q02", `${showEvidence.promptDa} ${showEvidence.contextDa}`, showEvidence.answerDa, "Choose the verb that matches the evidential strength.", "nuance", ["synonym-pick", showEvidence.id], "Resultatet støtter en tolkning, men lukker ikke sagen.", "Bankordet er kalibreret til evidens, der peger uden at bevise."), focusWord: "viser", context: showEvidence.contextDa, register: "formal", options: [...showEvidence.optionsDa] }),
      buildSynonymPick({ ...common("l20-m01-q03", `${tentativeThink.promptDa} ${tentativeThink.contextDa}`, tentativeThink.answerDa, "Choose the appropriately tentative reporting verb.", "nuance", ["synonym-pick", tentativeThink.id], "Taleren har en begrundet antagelse, ikke sikker viden.", "Det valgte ord markerer en forsigtig inferens."), focusWord: "tror", context: tentativeThink.contextDa, register: "formal", options: [...tentativeThink.optionsDa] }),
      buildChoice({ ...common("l20-m01-q04", "Hvilken kritik passer til én alvorlig metodefejl uden tegn på bedrag?", "Analysen er metodisk uforsvarlig.", "The analysis is methodologically indefensible.", "nuance", ["kritik", "proportionalitet"], "Angrib metoden hårdt, men opfind ikke en hensigt.", "Uforsvarlig er stærk faglig kritik; svindel ville tilføje udokumenteret forsæt."), options: ["Analysen er lidt pudsig.", "Analysen er metodisk uforsvarlig.", "Forfatteren begår bevidst svindel."] }),
      buildErrorHunt({ ...common("l20-m01-q05", "Find ordet, der gør en sandsynlighed til en dom.", "sandsynligvis", "The discrepancy is probably due to a measurement error.", "hedging", ["error-hunt", "sikkerhedsgrad"], "Dataene støtter forklaringen, men udelukker ikke andre.", "Sandsynligvis matcher evidensen; utvivlsomt foregiver fuld sikkerhed.", "produce"), sentenceTokens: ["Afvigelsen", "skyldes", "utvivlsomt", "en", "målefejl."], errorIndex: 2, correction: "sandsynligvis" }),
      buildOrder({ ...common("l20-m01-q06", "Byg den præcise reservation.", "Resultatet er robust inden for modellen, men kan ikke uden videre generaliseres.", "The result is robust within the model but cannot simply be generalised.", "hedging", ["forbehold", "generalisering"], "Bevar styrken lokalt og begræns rækkevidden.", "Kontrasten siger præcist, hvor resultatet er stærkt, og hvor det ikke endnu rækker.", "produce"), tokens: ["Resultatet er robust", "inden for modellen,", "men kan ikke", "uden videre generaliseres."], acceptedAnswers: ["Resultatet er robust inden for modellen, men kan ikke uden videre generaliseres."] }),
      buildTransform({ ...common("l20-m01-q07", "Kalibrer den bombastiske konklusion.", "Dataene tyder på, at tiltaget kan have reduceret fraværet.", "The data suggest that the measure may have reduced absence.", "hedging", ["transform", "evidens"], "Skru både evidensverbet og kausaliteten ned.", "Tyder på og kan have markerer to uafhængige usikkerheder: mønsteret og årsagsforholdet.", "produce"), sourceSentence: "Dataene beviser, at tiltaget fjernede fraværet.", instruction: "Omskriv, så en foreløbig korrelation ikke bliver til sikker årsag.", acceptedAnswers: ["Dataene tyder på, at tiltaget kan have reduceret fraværet."] }),
      buildFreeRewrite({ ...common("l20-m01-q08", "Omskriv den vrede anmeldelse til bidende B2-dansk.", "AI-bedømt omskrivning", "Rewrite the angry review into biting B2-level Danish.", "nuance", ["free-rewrite", "kritik", "register"], "Bevar dommen, men erstat personangreb med konkrete svagheder.", "Svaret vurderes på styrke, præcision, evidens og fravær af tomme fornærmelser.", "produce"), sourceText: "Denne idiotiske rapport er totalt skrald, og alle bag den burde fyres.", instruction: "Skriv 45–70 ord: hårdt, sagligt og med mindst ét kalibreret forbehold.", minWords: 45, aiPolicy: { mode: "grade", task: "free-rewrite", skipWhenUnavailable: true, requiredFacts: ["alvorlig kritik", "konkret metodisk svaghed", "kalibreret forbehold", "ingen personangreb"] } }),
    ]),
    mission("l20-m02", "Det er netop her", "Kløvning, partikler og informationsfokus", "target", [
      buildChoice({ ...common("l20-m02-q01", "Hvad retter “Det var tidsplanen, der væltede projektet” ?", "En antagelse om, at noget andet var hovedårsagen.", "An assumption that something else was the main cause.", "sætningskløvning", ["fokus", "der"], "Det fremhævede led står mellem det var og relativleddet.", "Kløvningen gør tidsplanen til kontrastfokus."), options: ["En antagelse om, at noget andet var hovedårsagen.", "Projektets grammatiske køn.", "At tidsplanen stadig står op."] }),
      buildOrder({ ...common("l20-m02-q02", "Byg kløvningen med stedfokus.", "Det var på kajen, at den afgørende fejl opstod.", "It was on the quay that the decisive error occurred.", "sætningskløvning", ["stedfokus", "at"], "Et stedsled efterfølges her af at-leddet.", "På kajen bliver kontrastfokus, mens resten af hændelsen er baggrund.", "produce"), tokens: ["Det var", "på kajen,", "at den afgørende fejl", "opstod."], acceptedAnswers: ["Det var på kajen, at den afgørende fejl opstod."] }),
      buildErrorHunt({ ...common("l20-m02-q03", "Find relativordet, der ikke kan være subjekt her.", "der", "It was Nora who discovered the discrepancy.", "sætningskløvning", ["error-hunt", "der"], "Det fremhævede led udfører handlingen.", "Der fungerer som subjekt i kløvningens relativled; som kræver et synligt eller underforstået subjekt på anden måde.", "produce"), sentenceTokens: ["Det", "var", "Nora,", "som", "opdagede", "afvigelsen."], errorIndex: 3, correction: "der" }),
      buildChoice({ ...common("l20-m02-q04", "Hvad gør jo i: “Det er jo netop dokumentationen, der mangler” ?", "Det fremstiller manglen som en fælles eller allerede etableret præmis.", "It presents the missing documentation as shared or established information.", "modalpartikler", ["jo", "fælles-viden"], "Partiklen ændrer relationen til modtageren, ikke dokumentets eksistens.", "Jo appellerer til en fælles præmis; netop skærper fokus."), options: ["Det gør sætningen til fortid.", "Det fremstiller manglen som en fælles eller allerede etableret præmis.", "Det ophæver negationen."] }),
      buildOrder({ ...common("l20-m02-q05", "Byg den forsigtige korrektion med vel.", "Det er vel prisen, vi bør undersøge først.", "It is presumably the price we should examine first.", "modalpartikler", ["vel", "objektfokus"], "Vel søger blød bekræftelse; objektets relativord kan udelades.", "Konstruktionen kombinerer tentative fælles forventning med fokus på prisen.", "produce"), tokens: ["Det er vel", "prisen,", "vi bør undersøge", "først."], acceptedAnswers: ["Det er vel prisen, vi bør undersøge først."] }),
      buildTransform({ ...common("l20-m02-q06", "Flyt fokus fra person til tidspunkt.", "Det var efter kontrollen, at Maja ændrede loggen.", "It was after the inspection that Maja changed the log.", "sætningskløvning", ["transform", "tidsfokus"], "Placér tidsleddet i fokuspositionen.", "Kløvningen korrigerer nu hvornår, ikke hvem.", "produce"), sourceSentence: "Det var Maja, der ændrede loggen efter kontrollen.", instruction: "Fremhæv tidspunktet efter kontrollen.", acceptedAnswers: ["Det var efter kontrollen, at Maja ændrede loggen."] }),
      buildChoice({ ...common("l20-m02-q07", "Hvilken version lyder insisterende, men stadig kollegial?", "Det er da den åbne ventil, vi skal se på først.", "It is the open valve we really should look at first.", "modalpartikler", ["da", "tone"], "Da kan skubbe på en fælles handling.", "Sætningen er tydelig og insisterende uden direkte at nedgøre modtageren."), options: ["Se nu ventilen, din klovn.", "Det er da den åbne ventil, vi skal se på først.", "Ventilen eksisterer eventuelt."] }),
      buildMicroDialogue({ ...common("l20-m02-q08", "Overbevis en erfaren kollega, der tror, du fokuserer på det forkerte spor.", "AI-bedømt dialog", "Convince an experienced colleague who thinks you are focusing on the wrong lead.", "fokusdialog", ["micro-dialogue", "kløvning", "partikler"], "Brug fokus til at korrigere uden at ydmyge.", "Dialogen vurderes på kløvning, passende modalpartikler, evidens og bevaret samarbejde.", "produce"), persona: "En skarp senioranalytiker, der afviser status, men reagerer positivt på præcise kontraster.", hiddenGoal: "Få en fælles kontrol af tidsstemplet uden at påstå, at hele hendes analyse er forkert.", turns: 3, minWords: 36, aiPolicy: { mode: "grade", task: "micro-dialogue", skipWhenUnavailable: true, persona: "skarp senioranalytiker", hiddenGoal: "opnå fælles kontrol af tidsstemplet" } }),
    ], 940),
    mission("l20-m03", "Argumentets skrog", "Påstand, belæg, hjemmel og modargument", "layers", [
      buildChoice({ ...common("l20-m03-q01", "Hvilket led er belæg i argumentet? ‘Vi bør lukke kajen, fordi vinden nu overstiger grænsen i manualen.’", "vinden overstiger grænsen i manualen", "the wind exceeds the limit in the manual", "argumentation", ["belæg", "påstand"], "Belægget er den oplysning, som anbefalingen hviler på.", "Vindmålingen og manualgrænsen støtter påstanden om lukning."), options: ["vi bør lukke kajen", "vinden overstiger grænsen i manualen", "fordi"] }),
      buildEvidentialTag({ ...common("l20-m03-q02", "Markér kildestatus for argumentets datapunkt.", "udledt", "Tag the source status of the argument's data point.", "argumentation", ["evidential-tag", "inferens"], "Må skyldes viser en slutning fra mønsteret.", "Påstanden er infereret, ikke direkte observeret."), statement: "De samtidige udfald må skyldes en fælles strømforsyning.", sourceStatus: "inferred", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildOrder({ ...common("l20-m03-q03", "Byg argumentet fra belæg til kalibreret påstand.", "Tre uafhængige sensorer viser trykfald; derfor bør røret undersøges, selv om årsagen endnu er ukendt.", "Three independent sensors show a pressure drop; therefore the pipe should be examined even though the cause remains unknown.", "argumentation", ["belæg", "konklusion", "forbehold"], "Lad handlingen være stærk, selv om årsagen er usikker.", "Argumentet skelner mellem sikker observation, proportionel anbefaling og ukendt årsag.", "produce"), tokens: ["Tre uafhængige sensorer", "viser trykfald;", "derfor bør røret undersøges,", "selv om årsagen", "endnu er ukendt."], acceptedAnswers: ["Tre uafhængige sensorer viser trykfald; derfor bør røret undersøges, selv om årsagen endnu er ukendt."] }),
      buildErrorHunt({ ...common("l20-m03-q04", "Find konnektoren, der vender argumentets relation forkert.", "derfor", "The sample is biased; therefore the estimate should not be generalised.", "argumentation", ["error-hunt", "konsekvens"], "Anden del følger som konsekvens af den første.", "Derfor markerer følge; desuden ville blot tilføje et sideløbende punkt.", "produce"), sentenceTokens: ["Stikprøven", "er", "skæv;", "desuden", "bør", "estimatet", "ikke", "generaliseres."], errorIndex: 3, correction: "derfor" }),
      buildTextOrder({ ...common("l20-m03-q05", "Ordne seks afsnit til et komplet argument.", "a>b>c>d>e>f", "Order six paragraphs into a complete argument.", "argumentation", ["text-order", "langtekst"], "Gå fra problem og data til hjemmel, modargument, svar og anbefaling.", "Strukturen gør inferensen synlig og lader modargumentet påvirke den endelige, begrænsede anbefaling.", "produce"), sentences: [{ id: "a", text: "Havnen overvejer at automatisere nattevagten." }, { id: "b", text: "Pilotforsøget registrerede 18 procent flere tekniske fejl, men færre falske alarmer." }, { id: "c", text: "En sikkerhedsordning bør reducere alvorlige oversete fejl, ikke blot det samlede alarmtal." }, { id: "d", text: "Leverandøren indvender, at personalet endnu ikke var fuldt uddannet." }, { id: "e", text: "Det kan forklare en del af forskellen, men ikke de fejl, systemet slet ikke viste." }, { id: "f", text: "Automatiseringen bør derfor kun udvides sammen med bemandet kontrol og en ny test." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["d", "a", "f", "c", "b", "e"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildChoice({ ...common("l20-m03-q06", "Hvilket modargument er relevant?", "Forsøget varede kun to uger og dækkede ikke vintervejr.", "The trial lasted only two weeks and did not cover winter weather.", "argumentation", ["modargument", "relevans"], "Det skal udfordre bevisets rækkevidde, ikke emnets popularitet.", "Varighed og vejr begrænser direkte generaliseringen af forsøget."), options: ["Leverandørens logo er grimt.", "Forsøget varede kun to uger og dækkede ikke vintervejr.", "Min nabo kan ikke lide robotter."] }),
      buildTransform({ ...common("l20-m03-q07", "Gør konklusionen gyldig i forhold til belægget.", "Undersøgelsen støtter en mulig sammenhæng mellem søvn og fejl blandt de målte nattevagter.", "The study supports a possible association between sleep and errors among the measured night guards.", "argumentation", ["transform", "rækkevidde"], "Begræns både kausalitet og population.", "Mulig sammenhæng undgår sikker årsag; blandt de målte nattevagter afgrænser populationen.", "produce"), sourceSentence: "Undersøgelsen beviser, at søvn altid forhindrer fejl hos alle.", instruction: "Kalibrer kausalitet og rækkevidde.", acceptedAnswers: ["Undersøgelsen støtter en mulig sammenhæng mellem søvn og fejl blandt de målte nattevagter."] }),
      buildExplainWhy({ ...common("l20-m03-q08", "Forklar, hvorfor en stærk anbefaling kan hvile på usikker årsag.", "AI-bedømt forklaring", "Explain why a strong recommendation can rest on uncertain causation.", "argumentation", ["explain-why", "risiko"], "Skeln mellem sikkerhed om mekanismen og prisen ved at vente.", "Svaret vurderes på beslutning under usikkerhed, proportionalitet, reversibilitet og dokumenteret risiko.", "produce"), claim: "Man kan kræve en midlertidig sikkerhedsforanstaltning uden at påstå, at årsagen er endeligt bevist.", requiredConcepts: ["observeret risiko", "usikker mekanisme", "proportional midlertidig handling", "ny test"], minWords: 70, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["risiko kan være dokumenteret", "årsag kan være usikker", "handlingen bør være proportional og reviderbar"] } }),
    ], 960),
    mission("l20-m04", "Den sidste formulering", "Syntese under pres", "star", [
      buildChoice({ ...common("l20-m04-q01", "Vælg åbningen, der både tager ansvar og holder analysen åben.", "Vi overså advarslen; nu må vi fastlægge hvorfor og forhindre en gentagelse.", "We missed the warning; now we must determine why and prevent a recurrence.", "syntese", ["ansvar", "handling"], "Indrøm det kendte uden at foregive en færdig årsagsanalyse.", "Sætningen forener ansvar, undersøgelse og fremadrettet handling."), options: ["Ingen kunne gøre noget.", "Vi overså advarslen; nu må vi fastlægge hvorfor og forhindre en gentagelse.", "Det var helt sikkert én idiots skyld."] }),
      buildOrder({ ...common("l20-m04-q02", "Byg den afsluttende syntese.", "Det er ikke én fejl, men samspillet mellem tidspres, uklar instruktion og manglende kontrol, der forklarer forløbet.", "It is not one error but the interaction of time pressure, unclear instructions, and missing control that explains the sequence.", "syntese", ["kløvning", "flerårsag"], "Brug kløvning til at korrigere idéen om én årsag.", "Konstruktionen fokuserer et flerleddet samspil og afviser en bekvem enkeltforklaring.", "produce"), tokens: ["Det er ikke én fejl,", "men samspillet mellem tidspres,", "uklar instruktion og manglende kontrol,", "der forklarer forløbet."], acceptedAnswers: ["Det er ikke én fejl, men samspillet mellem tidspres, uklar instruktion og manglende kontrol, der forklarer forløbet."] }),
      buildErrorHunt({ ...common("l20-m04-q03", "Find ordet, der skjuler ansvar bag passiv tåge.", "Ledelsen", "Management removed the warning from the procedure.", "klart sprog", ["error-hunt", "aktør"], "Dokumenterne navngiver den besluttende aktør.", "Ledelsen gør ansvaret synligt; man ville skjule den dokumenterede aktør.", "produce"), sentenceTokens: ["Man", "fjernede", "advarslen", "fra", "proceduren."], errorIndex: 0, correction: "Ledelsen" }),
      buildEvidentialTag({ ...common("l20-m04-q04", "Markér kildestatus i slutnotatet.", "gengivet", "Tag the source status in the final note.", "evidentialitet", ["evidential-tag", "rapport"], "Oplysningen tilskrives to protokoller.", "Kilden er dokumenteret, men afsenderen rapporterer den indirekte."), statement: "Ifølge begge protokoller blev nødproceduren ikke fulgt.", sourceStatus: "reported", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildChoice({ ...common("l20-m04-q05", "Hvilken slutning er strengest og mest retfærdig?", "Den dokumenterede forsømmelse kræver ansvar; den udokumenterede hensigt kræver tavshed.", "The documented negligence demands accountability; the undocumented intent demands silence.", "syntese", ["etik", "evidens"], "Døm handlingen på beviset, ikke motivet på fantasien.", "Sætningen er kompromisløs om det dokumenterede og disciplineret om det ukendte."), options: ["Alle havde gode intentioner, så skaden tæller ikke.", "Den dokumenterede forsømmelse kræver ansvar; den udokumenterede hensigt kræver tavshed.", "Motivet er sikkert ondt, fordi resultatet var dårligt."] }),
      buildTextOrder({ ...common("l20-m04-q06", "Ordne den endelige havnerapport.", "a>b>c>d>e>f", "Order the final harbour report.", "syntese", ["text-order", "slutrapport"], "Fakta før fortolkning; begrænsning før anbefaling.", "Rækkefølgen gør rapporten efterprøvbar, kildebevidst og handlingsdygtig.", "produce"), sentences: [{ id: "a", text: "Klokken 4.12 mistede tre sensorer samtidig forbindelsen." }, { id: "b", text: "Loggen viser, at reservesystemet startede 47 sekunder senere." }, { id: "c", text: "Forsinkelsen kan forklare trykstigningen, men ikke den første afbrydelse." }, { id: "d", text: "Ifølge teknikeren var et kabel angiveligt blevet flyttet dagen før." }, { id: "e", text: "Kameraet dækker ikke kabelskabet, så aktøren kan endnu ikke fastslås." }, { id: "f", text: "Skabet bør forsegles, og tidsforsinkelsen testes under uafhængigt tilsyn." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["d", "b", "f", "a", "e", "c"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildCompress({ ...common("l20-m04-q07", "Komprimer konklusionen til højst 38 danske ord uden at miste ansvar eller usikkerhed.", "AI-bedømt komprimering", "Compress the conclusion to no more than 38 Danish words without losing accountability or uncertainty.", "syntese", ["compress", "slutrapport"], "Bevar fund, begrænsning, ansvarlig handling og næste test.", "Svaret vurderes på fire obligatoriske fakta, præcis modalitet og ordgrænsen.", "produce"), sourceText: "Undersøgelsen dokumenterer, at alarmens tidsgrænse blev ændret uden den krævede godkendelse. Den viser ikke, hvem der gjorde det eller hvorfor. Ledelsen skal genetablere kontrollen straks og lade en uafhængig tekniker teste både grænsen og logningen.", maxWords: 38, requiredFacts: ["ugodkendt ændring", "aktør og motiv ukendt", "kontrol genetableres", "uafhængig test"], minWords: 22, aiPolicy: { mode: "grade", task: "compress", skipWhenUnavailable: true, maxWords: 38, requiredFacts: ["ugodkendt alarmændring", "ukendt hvem og hvorfor", "straks genetablere", "uafhængig test"] } }),
      buildFreeRewrite({ ...common("l20-m04-q08", "Skriv din endelige formulering til havnerådet.", "AI-bedømt afslutning", "Write your final statement to the harbour council.", "syntese", ["free-rewrite", "argumentation", "register"], "Saml evidens, begrænsning, ansvar og en konkret vej frem.", "Svaret vurderes som ekspansionens samlede B2-produktion: nuance, fokus, kildeafstand, sammenhæng og handlingskraft.", "produce"), sourceText: "Rådet skal beslutte, om terminalen genåbner efter en alvorlig fejl. Fejlen er dokumenteret; årsagen er delvis ukendt; en midlertidig sikker drift er mulig med ekstra kontrol.", instruction: "Skriv 90–130 ord til et offentligt møde. Vær myndig, menneskelig og præcis; medtag et modargument og et svar.", minWords: 90, aiPolicy: { mode: "grade", task: "free-rewrite", skipWhenUnavailable: true, requiredFacts: ["fejlen er dokumenteret", "årsagen er delvis ukendt", "midlertidig drift kræver ekstra kontrol", "modargument og svar", "konkret beslutning"] } }),
    ], 980),
  ],
};
