import {
  buildChoice, buildCompress, buildErrorHunt, buildEvidentialTag, buildExplainWhy,
  buildInput, buildMicroDialogue, buildOrder, buildTextOrder, buildTransform,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 2): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 700) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });

export const level16: CourseLevel = {
  id: "level-16", eyebrow: "B1 · Niveau 16", title: "Sagt og gengivet",
  description: "Gengiv andres ord uden at stjæle deres sikkerhed, tone eller ansvar.",
  color: "#55a9a1", unlockXp: 16800,
  missions: [
    mission("l16-m01", "Hvem sagde hvad?", "Fra direkte tale til præcis gengivelse", "message", [
      buildTransform({ ...common("l16-m01-q01", "Gengiv udsagnet indirekte.", "Lea sagde, at hun arbejdede hjemme.", "Lea said that she was working from home.", "indirekte tale", ["at-sætning", "tempusskift"], "Skift både pronomen og tidsperspektiv.", "Jeg bliver til hun, og arbejder forskydes til arbejdede efter datidsverbet sagde.", "produce"), sourceSentence: "Lea: ‘Jeg arbejder hjemme.’", instruction: "Begynd med Lea sagde, at ...", acceptedAnswers: ["Lea sagde, at hun arbejdede hjemme."] }),
      buildChoice({ ...common("l16-m01-q02", "Vælg: Omar spurgte, ___ mødet stadig var aflyst.", "om", "Omar asked whether the meeting was still cancelled.", "indirekte spørgsmål", ["om-sætning"], "Spørgsmålet kan besvares med ja eller nej.", "Om indleder et indirekte ja/nej-spørgsmål."), options: ["at", "om", "som", "der"] }),
      buildOrder({ ...common("l16-m01-q03", "Byg det indirekte spørgsmål.", "Hun spurgte, hvorfor toget ikke var kommet.", "She asked why the train had not arrived.", "indirekte spørgsmål", ["hvorfor", "ikke-position"], "I ledsætningen står ikke før det finite verbum.", "Spørgeordet bevares, mens ledsætningsrækkefølgen giver toget ikke var.", "produce", 3), tokens: ["Hun spurgte,", "hvorfor", "toget ikke", "var kommet."], acceptedAnswers: ["Hun spurgte, hvorfor toget ikke var kommet."] }),
      buildErrorHunt({ ...common("l16-m01-q04", "Find ordstillingsfejlen i referatet.", "han kunne", "Mads asked whether he could leave early.", "indirekte spørgsmål", ["error-hunt", "ledsætning"], "Efter om kommer subjektet før verbet.", "Et indirekte spørgsmål har ledsætningsordstilling: om han kunne, ikke om kunne han.", "produce"), sentenceTokens: ["Mads", "spurgte,", "om", "kunne han", "gå", "tidligt."], errorIndex: 3, correction: "han kunne" }),
      buildChoice({ ...common("l16-m01-q05", "Hvilken gengivelse holder afstand til et ubekræftet løfte?", "Direktøren hævdede, at alle ville få bonus.", "The director claimed that everyone would receive a bonus.", "gengivelsesverber", ["hævdede", "kildeafstand"], "Vælg et verbum, der ikke godkender påstanden som sand.", "Hævdede tilskriver udsagnet til direktøren og signalerer mulig tvivl."), options: ["Direktøren beviste, at alle ville få bonus.", "Direktøren hævdede, at alle ville få bonus.", "Alle får naturligvis bonus."] }),
      buildInput({ ...common("l16-m01-q06", "Udfyld det indirekte spørgsmål: Journalisten ville vide, ___ tallene kom fra.", "hvor", "The journalist wanted to know where the figures came from.", "indirekte spørgsmål", ["spørgeord", "kilde"], "Bevar spørgsmålets stedord.", "Hvor indleder et åbent indirekte spørgsmål om oprindelse.", "produce"), acceptedAnswers: ["hvor", "Hvor"] }),
      buildTransform({ ...common("l16-m01-q07", "Gengiv ordren uden at citere.", "Vagten bad os om at forlade området.", "The guard asked us to leave the area.", "indirekte tale", ["bede-om-at", "ordre"], "En ordre gengives ofte med bede nogen om at.", "Konstruktionen bevarer handlingen, men gør talerhandlingen eksplicit.", "produce", 3), sourceSentence: "Vagten: ‘Forlad området nu.’", instruction: "Brug bad os om at.", acceptedAnswers: ["Vagten bad os om at forlade området."] }),
      buildMicroDialogue({ ...common("l16-m01-q08", "Før en kort samtale med en kollega, der kun vil citeres anonymt.", "AI-bedømt dialog", "Have a short conversation with a colleague who only agrees to be quoted anonymously.", "kildesamtale", ["micro-dialogue", "kildebeskyttelse"], "Stil præcise spørgsmål uden at love mere, end du kan holde.", "Dialogen vurderes på kildeafklaring, indirekte gengivelse og respekt for grænsen.", "produce", 3), persona: "En nervøs kollega, der har set et sikkerhedsproblem, men frygter chefen.", hiddenGoal: "Få tilladelse til at gengive de verificerbare fakta anonymt uden at presse på for et navn.", turns: 3, minWords: 30, aiPolicy: { mode: "grade", task: "micro-dialogue", skipWhenUnavailable: true, persona: "nervøs anonym kilde", hiddenGoal: "afklar fakta og citattilladelse uden pres" } }),
    ]),
    mission("l16-m02", "Kilden i sætningen", "Ifølge, angiveligt og andre afstandsmål", "book", [
      buildEvidentialTag({ ...common("l16-m02-q01", "Markér kildestatus for udsagnet.", "gengivet", "Tag the source status of the statement.", "evidentialitet", ["evidential-tag", "ifølge"], "Ifølge placerer oplysningerne hos en navngiven kilde.", "Taleren gengiver rapporten, men påstår ikke selv at have observeret hændelsen."), statement: "Ifølge politiets rapport forlod bilen området klokken 22.14.", sourceStatus: "reported", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildEvidentialTag({ ...common("l16-m02-q02", "Markér kildestatus for udsagnet.", "usikker", "Tag the source status of the statement.", "evidentialitet", ["evidential-tag", "angiveligt"], "Angiveligt advarer om, at oplysningen ikke er bekræftet.", "Påstanden cirkulerer, men afsenderen tager tydelig afstand fra dens sandhed."), statement: "Leverandøren har angiveligt skjult to fakturaer.", sourceStatus: "uncertain", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildChoice({ ...common("l16-m02-q03", "Hvilken sætning skelner klarest mellem observation og slutning?", "Kameraet viser en tom gang; derfor antager vagten, at personen brugte bagdøren.", "The camera shows an empty corridor; therefore the guard assumes the person used the back door.", "evidentialitet", ["observation", "inferens"], "Find både et datagrundlag og en markeret slutning.", "Viser rapporterer observationen, mens antager markerer den efterfølgende inferens."), options: ["Kameraet beviser alt.", "Kameraet viser en tom gang; derfor antager vagten, at personen brugte bagdøren.", "Personen brugte selvfølgelig bagdøren."] }),
      buildOrder({ ...common("l16-m02-q04", "Byg en kildebevidst nyhedssætning.", "Ifølge kommunen bliver broen angiveligt forsinket igen.", "According to the municipality, the bridge will reportedly be delayed again.", "evidentialitet", ["ifølge", "angiveligt"], "Navngiv kilden først og behold usikkerheden omkring resultatet.", "Ifølge placerer kilden; angiveligt begrænser afsenderens egen sikkerhed.", "produce", 3), tokens: ["Ifølge kommunen", "bliver broen", "angiveligt", "forsinket igen."], acceptedAnswers: ["Ifølge kommunen bliver broen angiveligt forsinket igen."] }),
      buildErrorHunt({ ...common("l16-m02-q05", "Find det ord, der gør referatet mere sikkert end kilden tillader.", "muligvis", "The witness said the driver may have worn a cap.", "evidentialitet", ["error-hunt", "sikkerhedsgrad"], "Vidnet var ikke sikkert.", "Muligvis bevarer vidnets usikkerhed; helt sikkert opfinder en styrke, der ikke findes i kilden.", "produce"), sentenceTokens: ["Vidnet", "sagde,", "at", "føreren", "helt sikkert", "havde", "en", "kasket", "på."], errorIndex: 4, correction: "muligvis" }),
      buildInput({ ...common("l16-m02-q06", "Udfyld kildemarkøren: ___ eksperterne kan revnen vokse i frostvejr.", "Ifølge", "According to the experts, the crack may grow in freezing weather.", "evidentialitet", ["ifølge", "kilde"], "Sæt kilden foran påstanden.", "Ifølge følges af en nominal kilde og overtager ikke selv sandhedsansvaret.", "produce"), acceptedAnswers: ["Ifølge", "ifølge"] }),
      buildExplainWhy({ ...common("l16-m02-q07", "Forklar på dansk, hvorfor “angiveligt” kan være etisk vigtigt.", "AI-bedømt forklaring", "Explain in Danish why 'angiveligt' can be ethically important.", "evidentialitet", ["explain-why", "etik"], "Tænk på både den omtalte person og læserens sikkerhedsvurdering.", "Forklaringen vurderes på kildeafstand, usikkerhed og risikoen ved at fremstille en påstand som fakta.", "produce", 3), claim: "Ordet ‘angiveligt’ er ikke bare pynt i en anklage.", requiredConcepts: ["usikker kilde", "beskyttelse mod falsk anklage", "læserens kalibrering"], minWords: 45, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["markerer usikkerhed", "adskiller påstand fra fakta", "mindsker overfortolkning"] } }),
      buildChoice({ ...common("l16-m02-q08", "Hvilken rubrik er ansvarlig, før undersøgelsen er afsluttet?", "Firmaet kan have brudt reglerne, viser foreløbig rapport", "The company may have broken the rules, a preliminary report shows.", "journalistisk register", ["hedging", "rubrik"], "Bevar både alvoren og den foreløbige status.", "Kan have og foreløbig markerer, at konklusionen endnu ikke er endelig."), options: ["FIRMAET ER SKYLDIGT!", "Firmaet kan have brudt reglerne, viser foreløbig rapport", "Der skete måske et eller andet"] }),
    ], 720),
    mission("l16-m03", "Tiden flytter med", "Tempusskift og tidsankre i gengivelse", "layers", [
      buildTransform({ ...common("l16-m03-q01", "Flyt udsagnet tilbage i fortællingens tid.", "Hun sagde, at hun havde sendt filen dagen før.", "She said that she had sent the file the day before.", "tempusskift", ["pluskvamperfektum", "dagen-før"], "Både handlingen og tidsordet ligger før sagde.", "Har sendt bliver havde sendt; i går bliver dagen før i den nye fortællesituation.", "produce", 3), sourceSentence: "Hun sagde: ‘Jeg har sendt filen i går.’", instruction: "Gengiv indirekte fra et senere tidspunkt.", acceptedAnswers: ["Hun sagde, at hun havde sendt filen dagen før."] }),
      buildChoice({ ...common("l16-m03-q02", "Vælg den korrekte tidsforskydning: ‘Vi kommer i morgen,’ sagde de mandag.", "De sagde mandag, at de ville komme dagen efter.", "They said on Monday that they would come the next day.", "tempusskift", ["ville", "dagen-efter"], "Flyt fremtiden set fra et datidspunkt.", "Kommer forskydes til ville komme, og i morgen bliver dagen efter."), options: ["De sagde, at de kommer i går.", "De sagde mandag, at de ville komme dagen efter.", "De siger mandag, at vi kom i morgen."] }),
      buildOrder({ ...common("l16-m03-q03", "Byg gengivelsen med to tidslag.", "Han forklarede, at motoren var stoppet, før vagten nåede frem.", "He explained that the engine had stopped before the guard arrived.", "tempusskift", ["førdatid", "før"], "Motorstoppet sker før vagtens ankomst.", "Var stoppet markerer den tidligere hændelse i forhold til nåede.", "produce", 3), tokens: ["Han forklarede,", "at motoren", "var stoppet,", "før vagten", "nåede frem."], acceptedAnswers: ["Han forklarede, at motoren var stoppet, før vagten nåede frem."] }),
      buildErrorHunt({ ...common("l16-m03-q04", "Find tidsordet, der stadig står i den oprindelige talesituation.", "ugen efter", "She promised that the answer would come the following week.", "tempusskift", ["error-hunt", "tidsanker"], "Løftet blev gengivet flere måneder senere.", "Næste uge skal forankres i den daværende tale og bliver ugen efter.", "produce"), sentenceTokens: ["Hun", "lovede,", "at", "svaret", "ville", "komme", "næste uge."], errorIndex: 6, correction: "ugen efter" }),
      buildInput({ ...common("l16-m03-q05", "Udfyld: Han sagde, at han ___ ventet i tre timer.", "havde", "He said that he had been waiting for three hours.", "tempusskift", ["pluskvamperfektum"], "Ventetiden ligger før sagde.", "Havde ventet er førdatid og placerer forløbet før gengivelsesøjeblikket.", "produce"), acceptedAnswers: ["havde", "Havde"] }),
      buildTextOrder({ ...common("l16-m03-q06", "Sæt rapportens tidslinje i logisk rækkefølge.", "a>b>c>d>e", "Put the report timeline in logical order.", "tekstsammenhæng", ["text-order", "tidslinje"], "Skeln mellem hændelserne og den senere gengivelse.", "Rækkefølgen går fra alarm, afbrydelse og kontrol til chefens senere forklaring.", "produce", 3), sentences: [{ id: "a", text: "Klokken 8.03 lød alarmen." }, { id: "b", text: "Kort efter standsede pumpen." }, { id: "c", text: "Teknikeren havde allerede set trykfaldet." }, { id: "d", text: "Hun lukkede derfor ventilen." }, { id: "e", text: "Senere forklarede chefen, at hun havde forhindret en større skade." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["e", "b", "d", "a", "c"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildChoice({ ...common("l16-m03-q07", "Hvornår behøver dansk ikke et mekanisk tempusskift?", "Når udsagnet stadig gælder, og nutiden er vigtig for meningen.", "When the statement is still true and the present matters to the meaning.", "tempusskift", ["nutidsrelevans", "nuance"], "Dansk er mindre mekanisk end engelsk her.", "Nutid kan bevares efter sagde, hvis taleren tydeligt fastholder udsagnets aktuelle gyldighed."), options: ["Aldrig", "Når udsagnet stadig gælder, og nutiden er vigtig for meningen.", "Kun når subjektet er en fisk"] }),
      buildCompress({ ...common("l16-m03-q08", "Komprimer vidnets tidslinje til højst 28 danske ord uden at miste fakta.", "AI-bedømt komprimering", "Compress the witness timeline to no more than 28 Danish words without losing facts.", "komprimering", ["compress", "tempusskift"], "Bevar tidspunkt, rækkefølge og kildens usikkerhed.", "Svaret vurderes på alle obligatoriske fakta, korrekt tidsforhold og ordgrænsen.", "produce", 3), sourceText: "Vidnet sagde klokken 23, at hun omkring 22.40 havde hørt glas knuse. Fem minutter senere så hun muligvis en mørk bil køre mod nord.", maxWords: 28, requiredFacts: ["udsagnet blev givet klokken 23", "glas omkring 22.40", "bil fem minutter senere", "muligvis", "mod nord"], minWords: 16, aiPolicy: { mode: "grade", task: "compress", skipWhenUnavailable: true, maxWords: 28, requiredFacts: ["klokken 23", "22.40", "fem minutter senere", "muligvis mørk bil mod nord"] } }),
    ], 740),
    mission("l16-m04", "Referatet, der bider", "Kilder, tone og ansvar i en lang tekst", "target", [
      buildEvidentialTag({ ...common("l16-m04-q01", "Markér kildestatus.", "observeret", "Tag the source status.", "evidentialitet", ["evidential-tag", "observation"], "Afsenderen beskriver sin egen direkte iagttagelse.", "Jeg så angiver førstehåndsobservation, selv om fortolkningen stadig kan diskuteres."), statement: "Jeg så selv teknikeren åbne skabet klokken 14.12.", sourceStatus: "observed", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildEvidentialTag({ ...common("l16-m04-q02", "Markér kildestatus.", "udledt", "Tag the source status.", "evidentialitet", ["evidential-tag", "inferens"], "Konklusionen udledes af et spor.", "Må have forladt markerer en slutning, ikke en direkte observation."), statement: "Døren var låst indefra, så hun må have forladt stedet gennem vinduet.", sourceStatus: "inferred", options: ["observeret", "gengivet", "usikker", "udledt"] }),
      buildChoice({ ...common("l16-m04-q03", "Hvilken sætning er kynisk, men kildepræcis?", "Ledelsen kalder fyringerne en ‘tilpasning’; medarbejderne kalder dem fredag.", "Management calls the layoffs an 'adjustment'; the employees call them Friday.", "kildekontrast", ["tone", "kilde"], "Humoren må ikke udviske, hvem der siger hvad.", "Begge betegnelser tilskrives tydeligt deres kilder, mens kontrasten bærer den skarpe tone."), options: ["Alle ved, at ledelsen lyver.", "Ledelsen kalder fyringerne en ‘tilpasning’; medarbejderne kalder dem fredag.", "Fyringer er vist noget med arbejde."] }),
      buildOrder({ ...common("l16-m04-q04", "Byg en streng, men fair konklusion.", "Rapporten dokumenterer fejlen, men ikke hvem der kendte til den.", "The report documents the error, but not who knew about it.", "kildekritik", ["dokumentation", "begrænsning"], "Adskil det dokumenterede fra det ukendte.", "Men ikke afgrænser bevisets rækkevidde uden at svække det fund, der faktisk er dokumenteret.", "produce", 3), tokens: ["Rapporten", "dokumenterer fejlen,", "men ikke", "hvem der", "kendte til den."], acceptedAnswers: ["Rapporten dokumenterer fejlen, men ikke hvem der kendte til den."] }),
      buildErrorHunt({ ...common("l16-m04-q05", "Find gengivelsesverbet, der uberettiget godkender påstanden.", "påstod", "The supplier claimed that the defect was harmless.", "gengivelsesverber", ["error-hunt", "kildeafstand"], "Dokumenterne afgør endnu ikke sandheden.", "Påstod gengiver leverandørens udsagn; beviste ville gøre journalisten til garant.", "produce"), sentenceTokens: ["Leverandøren", "beviste,", "at", "fejlen", "var", "harmløs."], errorIndex: 1, correction: "påstod" }),
      buildTextOrder({ ...common("l16-m04-q06", "Byg et sammenhængende mini-referat af fem kilder.", "a>b>c>d>e", "Build a coherent mini-report from five source statements.", "tekstsammenhæng", ["text-order", "kilder"], "Start med hændelsen, fortsæt med kilderne, og slut med begrænsningen.", "Strukturen etablerer fakta, kontrasterer forklaringer og markerer til sidst, hvad ingen kilde kan afgøre.", "produce", 3), sentences: [{ id: "a", text: "Alarmen blev registreret klokken 6.18." }, { id: "b", text: "Ifølge vagten var porten allerede åben." }, { id: "c", text: "Teknikeren hævdede derimod, at hun havde låst den." }, { id: "d", text: "Kameraet viser kun gården, ikke selve låsen." }, { id: "e", text: "Det kan derfor endnu ikke fastslås, hvem der åbnede porten." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["c", "e", "a", "d", "b"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildChoice({ ...common("l16-m04-q07", "Hvilken afslutning behandler en modig kilde med værdighed?", "Kilden risikerede sit arbejde for at dokumentere forhold, offentligheden havde ret til at kende.", "The source risked their job to document matters the public had a right to know.", "kildeetik", ["nobel", "register"], "Varm tone kan stadig være præcis.", "Sætningen navngiver både risiko, handling og offentlig interesse uden heltedyrkelse."), options: ["Kilden sladrede endelig.", "Kilden risikerede sit arbejde for at dokumentere forhold, offentligheden havde ret til at kende.", "Kilden var 100 % perfekt."] }),
      buildExplainWhy({ ...common("l16-m04-q08", "Forklar, hvorfor et godt referat både kan være skarpt og retfærdigt.", "AI-bedømt forklaring", "Explain why a good report can be both sharp and fair.", "kildekritik", ["explain-why", "argumentation"], "Brug forskellen mellem kritik af en påstand og dom over en person.", "Svaret vurderes på kildegrundlag, proportional tone og tydelig adskillelse af fakta og vurdering.", "produce", 3), claim: "Retfærdig gengivelse kræver ikke tandløst sprog.", requiredConcepts: ["korrekt attribution", "bevisets grænser", "proportional kritik"], minWords: 55, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["kilde skal navngives eller afgrænses", "kritik skal følge dokumentation", "usikkerhed skal markeres"] } }),
    ], 760),
  ],
};
