import {
  buildChoice, buildCompress, buildErrorHunt, buildExplainWhy, buildInflectionForge,
  buildInput, buildOrder, buildTextOrder, buildTransform, buildWordForge,
} from "../builders.ts";
import type { BaseItem, CourseLevel, Difficulty, Modality } from "../types.ts";
import { buildInflectionForge as lexicalInflection, buildWordForge as lexicalWord } from "../../lexicalBanks.ts";

type Common = Pick<BaseItem, "id" | "prompt" | "answer" | "hint" | "explanation" | "translation" | "skill" | "tags" | "difficulty" | "modality">;
const common = (id: string, prompt: string, answer: string, translation: string, skill: string,
  tags: string[], hint: string, explanation: string, modality: Modality = "read", difficulty: Difficulty = 2): Common =>
  ({ id, prompt, answer, translation, skill, tags, hint, explanation, modality, difficulty });
const mission = (id: string, title: string, subtitle: string, icon: string, questions: CourseLevel["missions"][number]["questions"], xp = 800) =>
  ({ id, title, subtitle, icon, estimatedMinutes: 7, xp, questions });
const word = (id: string) => lexicalWord(id);
const working = word("cmp-arbejdsloes");
const safety = word("cmp-sikkerhedskontrol");
const child = word("cmp-barnevogn");
const harborWorker = word("cmp-havnearbejder");
const sunshine = word("cmp-solskin");
const coffee = word("cmp-kaffemaskine");
const comparative = lexicalInflection("inf-hoej-comparative");

export const level18: CourseLevel = {
  id: "level-18", eyebrow: "A2+ · Niveau 18", title: "Ordsmedjen",
  description: "Smed ord, afled betydning og vælg fugebogstavet, som om dansk havde udleveret en tegning. Det havde dansk ikke.",
  color: "#d6933d", unlockXp: 22300,
  missions: [
    mission("l18-m01", "To ord går ind", "Sammensætninger og det vigtigste led til sidst", "sparkles", [
      buildWordForge({ ...common("l18-m01-q01", working.promptDa, working.answerDa, "Build the Danish word for unemployed.", "ordsammensætning", ["word-forge", working.id], "Arbejd og løs bindes med s.", "Hovedleddet løs står sidst; fuge-s binder stammen til hovedet.", "produce"), morphemes: [working.firstStemDa, working.headDa], fugeelement: "s", acceptedAnswers: [working.answerDa] }),
      buildWordForge({ ...common("l18-m01-q02", safety.promptDa, safety.answerDa, "Build the Danish compound for security check.", "ordsammensætning", ["word-forge", safety.id], "Bevar hele førsteleddet sikkerhed.", "Sikkerhedskontrol bruger fuge-s mellem førsteled og hovedled.", "produce"), morphemes: [safety.firstStemDa, safety.headDa], fugeelement: "s", acceptedAnswers: [safety.answerDa] }),
      buildChoice({ ...common("l18-m01-q03", "Hvad er hovedleddet i “havnearbejder” ?", "arbejder", "worker", "ordsammensætning", ["hovedled", "betydning"], "Hovedleddet fortæller, hvilken slags ting eller person ordet er.", "En havnearbejder er først og fremmest en arbejder; havn afgrænser arbejdsstedet."), options: ["havn", "e", "arbejder", "havne"] }),
      buildWordForge({ ...common("l18-m01-q04", harborWorker.promptDa, harborWorker.answerDa, "Build the Danish compound for harbour worker.", "ordsammensætning", ["word-forge", harborWorker.id], "Her forbinder e de to led.", "Havnearbejder har fuge-e og hovedleddet arbejder.", "produce"), morphemes: [harborWorker.firstStemDa, harborWorker.headDa], fugeelement: "e", acceptedAnswers: [harborWorker.answerDa] }),
      buildErrorHunt({ ...common("l18-m01-q05", "Find den overflødige fuge og ret ordet.", "solskin", "Sunshine warmed the bench.", "ordsammensætning", ["error-hunt", "nul-fuge"], "Sol og skin står direkte sammen.", "Solskin dannes uden fugeelement.", "produce"), sentenceTokens: ["Solen", "gav", "os", "solsskin", "på", "bænken."], errorIndex: 3, correction: "solskin" }),
      buildWordForge({ ...common("l18-m01-q06", sunshine.promptDa, sunshine.answerDa, "Build the Danish compound for sunshine.", "ordsammensætning", ["word-forge", sunshine.id], "Prøv først uden ekstra bogstav.", "Solskin er et produktivt toleddet ord med nul-fuge.", "produce"), morphemes: [sunshine.firstStemDa, sunshine.headDa], fugeelement: "", acceptedAnswers: [sunshine.answerDa] }),
      buildOrder({ ...common("l18-m01-q07", "Byg analysen af et sammensat ord.", "I ordet brandalarm er alarm hovedleddet, mens brand beskriver faren.", "In the word fire alarm, alarm is the head while fire describes the danger.", "ordsammensætning", ["hovedled", "analyse"], "Start med hele ordet og navngiv derefter de to rollers forskel.", "Hovedleddet bestemmer ordklasse og grundbetydning; førsteleddet afgrænser typen.", "produce"), tokens: ["I ordet brandalarm", "er alarm hovedleddet,", "mens brand", "beskriver faren."], acceptedAnswers: ["I ordet brandalarm er alarm hovedleddet, mens brand beskriver faren."] }),
      buildChoice({ ...common("l18-m01-q08", "Hvilket nyt ord er umiddelbart forståeligt, selv om det lyder lidt fjollet?", "mødekageberedskab", "meeting-cake preparedness", "ordsammensætning", ["produktivitet", "humor"], "Dansk tillader lange, transparente kæder.", "Mødekageberedskab kan analyseres som beredskab for kage til møder; joken virker, fordi strukturen er gennemsigtig."), options: ["mødekageberedskab", "møde af kage bered", "beredmødekage", "kagen mødes"] }),
    ]),
    mission("l18-m02", "Den lille fuge", "-s-, -e- eller ingenting", "target", [
      buildWordForge({ ...common("l18-m02-q01", child.promptDa, child.answerDa, "Build the Danish compound for pram.", "fugeelementer", ["word-forge", child.id], "Barn skifter form i sammensætningen.", "Barnevogn bruger fuge-e mellem barn og vogn.", "produce"), morphemes: [child.firstStemDa, child.headDa], fugeelement: "e", acceptedAnswers: [child.answerDa] }),
      buildWordForge({ ...common("l18-m02-q02", coffee.promptDa, coffee.answerDa, "Build the Danish compound for coffee machine.", "fugeelementer", ["word-forge", coffee.id], "Kaffe ender allerede på e.", "Kaffemaskine føjer leddene direkte sammen uden et ekstra fugebogstav.", "produce"), morphemes: [coffee.firstStemDa, coffee.headDa], fugeelement: "", acceptedAnswers: [coffee.answerDa] }),
      buildChoice({ ...common("l18-m02-q03", "Vælg det etablerede ord.", "kærlighedsbrev", "love letter", "fugeelementer", ["fuge-s", "kærlighed"], "Det lange førsteled får ofte s.", "Kærlighedsbrev har fuge-s efter førsteleddet kærlighed."), options: ["kærlighedbrev", "kærlighedsbrev", "kærlighedebrev", "kærlighednbrev"] }),
      buildErrorHunt({ ...common("l18-m02-q04", "Find den forkerte fugeform.", "Hundesnoren", "The dog's lead hung by the door.", "fugeelementer", ["error-hunt", "fuge-e"], "Det etablerede ord har e mellem leddene.", "Hundesnor er normeret med fuge-e.", "produce"), sentenceTokens: ["Hundsnoren", "hang", "ved", "døren."], errorIndex: 0, correction: "Hundesnoren" }),
      buildInput({ ...common("l18-m02-q05", "Udfyld hele ordet: En plan for tider er en ___.", "tidsplan", "A plan of times is a schedule.", "fugeelementer", ["tidsplan", "fuge-s"], "Tid får s foran plan.", "Tidsplan er den etablerede sammensætning.", "produce"), acceptedAnswers: ["tidsplan", "Tidsplan"] }),
      buildChoice({ ...common("l18-m02-q06", "Hvorfor kan man ikke altid regne fugeelementet ud fra en universel regel?", "Det afhænger af etableret ordbrug, orddannelse og historiske mønstre.", "It depends on established usage, word formation, and historical patterns.", "fugeelementer", ["leksikalisering", "mønstre"], "Mønstre hjælper, men ordet har også en historie.", "Fugeelementer er delvis produktive og delvis leksikalske; derfor bør hele ord læres."), options: ["Fordi dansk bruger tilfældige emojis", "Det afhænger af etableret ordbrug, orddannelse og historiske mønstre.", "Fordi alle ord altid tager s"] }),
      buildTextOrder({ ...common("l18-m02-q07", "Ordne arbejdsgangen i Ordsmedjen.", "a>b>c>d>e", "Order the compound-building workflow.", "orddannelse", ["text-order", "strategi"], "Betydningen skal komme før stavningen.", "Processen går fra begreb og hovedled til førsteled, mulig fuge og kontrol i kontekst.", "produce", 3), sentences: [{ id: "a", text: "Afgør først, hvilket begreb du vil navngive." }, { id: "b", text: "Find derefter hovedleddet, som bestemmer ordets grundtype." }, { id: "c", text: "Vælg et førsteled, der afgrænser betydningen." }, { id: "d", text: "Kontrollér, om det etablerede ord kræver en fuge." }, { id: "e", text: "Læs til sidst hele ordet i en sætning." }], correctOrder: ["a", "b", "c", "d", "e"], tokens: ["d", "b", "e", "a", "c"], acceptedAnswers: ["a>b>c>d>e"] }),
      buildExplainWhy({ ...common("l18-m02-q08", "Forklar, hvorfor ‘sikkerhedkontrol’ er forståeligt, men stadig forkert.", "AI-bedømt forklaring", "Explain why 'sikkerhedkontrol' is understandable but still wrong.", "fugeelementer", ["explain-why", "sikkerhedskontrol"], "Skeln mellem kompositionel betydning og etableret form.", "Svaret vurderes på hovedled, fuge-s og forskellen mellem forståelighed og norm.", "produce", 3), claim: "Et sammensat ord kan være gennemsigtigt og alligevel unormeret.", requiredConcepts: ["sikkerhed + kontrol", "fuge-s", "etableret ordform"], minWords: 45, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["betydningen kan udledes", "korrekt form er sikkerhedskontrol", "fuge-s er nødvendig"] } }),
    ], 820),
    mission("l18-m03", "Forstavelse og efterklang", "u-, -lig, -bar, -hed og -løs", "layers", [
      buildChoice({ ...common("l18-m03-q01", "Hvad gør forstavelsen u- i ‘usikker’ ?", "Den negerer grundbetydningen.", "It negates the base meaning.", "afledning", ["u-", "negation"], "Sammenlign sikker med usikker.", "U- danner ofte et antonym ved at nægte grundordets egenskab."), options: ["Den gør ordet til datid.", "Den negerer grundbetydningen.", "Den gør ordet til flertal."] }),
      buildChoice({ ...common("l18-m03-q02", "Vælg det ord, der betyder ‘kan repareres’.", "reparerbar", "repairable", "afledning", ["-bar", "mulighed"], "Endelsen udtrykker mulighed for en handling.", "-bar føjes til verbets stamme og betyder, at noget kan udsættes for handlingen."), options: ["reparerlig", "reparerbar", "reparerhed", "reparerløs"] }),
      buildInput({ ...common("l18-m03-q03", "Dan et substantiv af ‘fri’ med betydningen freedom.", "frihed", "freedom", "afledning", ["-hed", "substantiv"], "Gør egenskaben til et abstrakt begreb.", "-hed danner substantivet frihed af adjektivet fri.", "produce"), acceptedAnswers: ["frihed", "Frihed"] }),
      buildErrorHunt({ ...common("l18-m03-q04", "Find afledningen, der lover det modsatte af meningen.", "fejlfrit", "The test is error-free, not without tests.", "afledning", ["error-hunt", "-fri"], "Det er fejl, produktet skal være fri for.", "Fejlfri betyder uden fejl; testløs ville betyde uden test.", "produce"), sentenceTokens: ["Systemet", "er", "testløst", "efter", "den", "grundige", "kontrol."], errorIndex: 2, correction: "fejlfrit" }),
      buildChoice({ ...common("l18-m03-q05", "Hvilken afledning er mest naturlig for ‘without hope’ ?", "håbløs", "hopeless", "afledning", ["-løs", "betydning"], "Endelsen betyder uden det, førsteleddet navngiver.", "Håbløs er en etableret afledning med -løs."), options: ["uhåb", "håbbar", "håbløs", "håbhed"] }),
      buildTransform({ ...common("l18-m03-q06", "Erstat omskrivningen med ét afledt ord.", "Planen er uigennemførlig.", "The plan is unworkable.", "afledning", ["transform", "u-", "-lig"], "Byg et adjektiv omkring stammen gennemfør.", "Uigennemførlig kombinerer u- med -lig og samler vurderingen i ét præcist ord.", "produce", 3), sourceSentence: "Planen kan ikke gennemføres i praksis.", instruction: "Brug et adjektiv med u- og -lig.", acceptedAnswers: ["Planen er uigennemførlig."] }),
      buildInflectionForge({ ...common("l18-m03-q07", `${comparative.promptDa} ${comparative.contextDa}`, comparative.answerDa, "Form the comparative of high.", "afledning og bøjning", ["inflection-forge", "højere"], "Bøjningen tilføjer -ere og ændrer vokalens længde i udtalen, ikke stavningen af stammen.", "Komparativ af høj er højere.", "produce"), lemma: "høj", targetDescription: "komparativ", acceptedAnswers: [...comparative.acceptableAnswersDa] }),
      buildCompress({ ...common("l18-m03-q08", "Komprimer produktbeskrivelsen til højst 22 danske ord med præcise afledninger.", "AI-bedømt komprimering", "Compress the product description to no more than 22 Danish words using precise derivations.", "afledning", ["compress", "-bar", "-løs"], "Erstat lange kan/uden-fraser med afledte adjektiver.", "Svaret vurderes på alle fakta, naturlige afledninger og ordgrænsen.", "produce", 3), sourceText: "Kassen kan genbruges, kan stables, har ingen giftige stoffer og kan ikke åbnes af børn uden værktøj.", maxWords: 22, requiredFacts: ["genbrugelig", "stabelbar", "giftfri", "børnesikker"], minWords: 10, aiPolicy: { mode: "grade", task: "compress", skipWhenUnavailable: true, maxWords: 22, requiredFacts: ["kan genbruges", "kan stables", "uden gift", "børn kan ikke åbne den"] } }),
    ], 840),
    mission("l18-m04", "Ord på værftet", "Længere kæder, tvetydighed og læsevenlighed", "book", [
      buildChoice({ ...common("l18-m04-q01", "Hvordan læses ‘havnesikkerhedskontrol’ mest naturligt?", "en kontrol af sikkerheden på havnen", "an inspection of harbour safety", "ordsammensætning", ["ordgrænser", "hovedled"], "Start fra sidste led og arbejd mod venstre.", "Kontrol er hovedled; sikkerhed afgrænser kontrollen, og havn afgrænser sikkerhedens område."), options: ["en sikker havn, der kontrollerer", "en kontrol af sikkerheden på havnen", "en havn lavet af kontrol"] }),
      buildOrder({ ...common("l18-m04-q02", "Byg den trinvise analyse.", "Hovedleddet er kontrol; sikkerhedskontrol er typen, og havn angiver området.", "The head is inspection; safety inspection is the type, and harbour gives the domain.", "ordsammensætning", ["analyse", "rekursion"], "Læs først kontrol, derefter sikkerhedskontrol, til sidst hele ordet.", "Danske sammensætninger kan udvides rekursivt fra højre mod venstre.", "produce", 3), tokens: ["Hovedleddet er kontrol;", "sikkerhedskontrol er typen,", "og havn", "angiver området."], acceptedAnswers: ["Hovedleddet er kontrol; sikkerhedskontrol er typen, og havn angiver området."] }),
      buildErrorHunt({ ...common("l18-m04-q03", "Find ordet, der bør deles for læsevenlighed.", "digital sikkerhedsplan.", "The municipality presented a digital safety plan.", "læsevenlighed", ["error-hunt", "tvetydighed"], "Digital beskriver planen, ikke nødvendigvis en ny ordstamme.", "En åben frase kan være bedre end et monsterord, når relationen ellers bliver tvetydig.", "produce"), sentenceTokens: ["Kommunen", "fremlagde", "en", "digitalsikkerhedsplan."], errorIndex: 3, correction: "digital sikkerhedsplan." }),
      buildChoice({ ...common("l18-m04-q04", "Hvornår bør en lang sammensætning forklares første gang?", "Når læseren ikke sikkert kan se ordgrænserne eller fagbetydningen.", "When readers cannot reliably see the boundaries or technical meaning.", "læsevenlighed", ["fagsprog", "modtager"], "Produktiv orddannelse er ikke det samme som fælles viden.", "En kort forklaring beskytter præcisionen uden at forbyde det nyttige fagord."), options: ["Aldrig", "Når læseren ikke sikkert kan se ordgrænserne eller fagbetydningen.", "Kun hvis ordet er på tre bogstaver"] }),
      buildInput({ ...common("l18-m04-q05", "Byg ordet: en alarm ved brand = ___.", "brandalarm", "fire alarm", "ordsammensætning", ["nul-fuge", "brandalarm"], "Sæt brand direkte foran hovedleddet alarm.", "Brandalarm dannes uden fugeelement.", "produce"), acceptedAnswers: ["brandalarm", "Brandalarm"] }),
      buildWordForge({ ...common("l18-m04-q06", "Byg ordet for en sag om forsikring.", "forsikringssag", "insurance case", "ordsammensætning", ["word-forge", "fuge-s"], "Forsikring får s foran sag.", "Forsikringssag bruger fuge-s, mens sag er hovedleddet.", "produce"), morphemes: ["forsikring", "sag"], fugeelement: "s", acceptedAnswers: ["forsikringssag"] }),
      buildTextOrder({ ...common("l18-m04-q07", "Ordne den lange værkstedsbeskrivelse, så den kan læses af et menneske.", "a>b>c>d>e>f", "Order the workshop description for readability.", "tekstsammenhæng", ["text-order", "fagsprog"], "Præsenter begrebet, delene og funktionen før advarslen.", "Teksten bygger ordets betydning lagvist og slutter med den praktiske begrænsning.", "produce", 3), sentences: [{ id: "a", text: "Værftet bruger en ny havnevandskvalitetsmåler." }, { id: "b", text: "Ordet har måler som hovedled." }, { id: "c", text: "Kvalitet fortæller, hvad apparatet vurderer." }, { id: "d", text: "Havnevand angiver, hvilken væske der undersøges." }, { id: "e", text: "Apparatet måler salt, olie og ilt hvert minut." }, { id: "f", text: "Det kan dog ikke identificere kilden til en forurening." }], correctOrder: ["a", "b", "c", "d", "e", "f"], tokens: ["e", "b", "f", "a", "d", "c"], acceptedAnswers: ["a>b>c>d>e>f"] }),
      buildExplainWhy({ ...common("l18-m04-q08", "Forklar, om ‘havnevandskvalitetsmåler’ er et godt ord i denne tekst.", "AI-bedømt forklaring", "Explain whether 'havnevandskvalitetsmåler' is a good word in this text.", "ordsammensætning", ["explain-why", "modtagerdesign"], "Vurder både præcision, gentagelse og læserens første møde med ordet.", "Svaret vurderes på morfologisk analyse, kontekst, læsevenlighed og en begrundet anbefaling.", "produce", 3), claim: "Det længste ord er hverken automatisk bedst eller værst.", requiredConcepts: ["måler som hovedled", "præcis reference", "førstegangs-forklaring", "målgruppe"], minWords: 60, aiPolicy: { mode: "grade", task: "explain-why", skipWhenUnavailable: true, requiredFacts: ["ordet er gennemsigtigt efter analyse", "det er kompakt ved gentagelse", "det bør forklares første gang"] } }),
    ], 860),
  ],
};
