"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, ChevronRight, CircuitBoard, FlaskConical, Ruler, Thermometer, Weight } from "lucide-react";
import type { ScenarioRun } from "@/lib/scenarioData";
import { evaluateScienceScenario, type ScienceAnswerValue, type ScienceScenarioSubmission } from "@/lib/scienceEngine";
import { scienceScenarioCases, type ScienceAnswerField, type ScienceScenarioCase } from "@/lib/scienceScenarioData";

type Props = { initialCaseId?: string; runs: readonly ScenarioRun[]; onStartAttempt?: (caseId: string) => boolean; onComplete: (run: ScenarioRun) => void; onExit: () => void };

function runId() { return typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `science-${Date.now()}`; }

const icons = { "resistor-code": CircuitBoard, "circuit-tuning": CircuitBoard, "measurement-uncertainty": Ruler, "lever-balance": Weight, "density-lab": FlaskConical, "thermal-design": Thermometer } as const;

export default function ScienceScenarioGame({ initialCaseId, runs, onStartAttempt, onComplete, onExit }: Props) {
  const [activeId, setActiveId] = useState<string | null>(initialCaseId ?? null);
  const solved = useMemo(() => new Set(runs.filter((run) => run.success).map((run) => run.caseId)), [runs]);
  if (!activeId) return <main className="science-root"><style>{css}</style><header className="science-header"><button onClick={onExit}><ArrowLeft size={19} /></button><div><span>SCIENCE + DANSK</span><h1>Forsøgshallen</h1><p>Læs manualen på dansk, arbejd med modellen og dokumentér et fysisk resultat.</p></div></header><section className="science-grid">{scienceScenarioCases.map((item) => { const Icon = icons[item.kind]; return <button style={{ "--science-accent": item.accent } as React.CSSProperties} key={item.id} onClick={() => setActiveId(item.id)}><Icon size={25} /><span>NIVEAU {item.courseLevel} · {item.level}</span><h2>{item.title}</h2><p>{item.description}</p><footer>{solved.has(item.id) ? <><Check size={15} /> Løst</> : <>Start forsøg <ChevronRight size={15} /></>}</footer></button>; })}</section></main>;
  const scenario = scienceScenarioCases.find((item) => item.id === activeId);
  if (!scenario) return null;
  return <ScienceRunner scenario={scenario} onStartAttempt={onStartAttempt} onComplete={onComplete} onBack={() => initialCaseId ? onExit() : setActiveId(null)} />;
}

function ScienceRunner({ scenario, onStartAttempt, onComplete, onBack }: { scenario: ScienceScenarioCase; onStartAttempt?: (caseId: string) => boolean; onComplete: (run: ScenarioRun) => void; onBack: () => void }) {
  const startedAt = useRef(new Date().toISOString());
  const attempted = useRef(false);
  useEffect(() => {
    if (attempted.current) return;
    attempted.current = true;
    onStartAttempt?.(scenario.id);
  }, [onStartAttempt, scenario.id]);
  const [submission, setSubmission] = useState<Record<string, Record<string, ScienceAnswerValue>>>({});
  const [activeStageId, setActiveStageId] = useState(scenario.stages[0]?.id ?? "");
  const [checkedStageIds, setCheckedStageIds] = useState<string[]>([]);
  const [submitted, setSubmitted] = useState(false);
  const evaluation = evaluateScienceScenario(scenario, submission as ScienceScenarioSubmission);
  const completed = new Set(evaluation.completedStageIds);
  const activeStage = scenario.stages.find((stage) => stage.id === activeStageId) ?? scenario.stages[0];
  const activeEvaluation = evaluation.stages.find((stage) => stage.stageId === activeStage.id);

  function update(field: ScienceAnswerField, value: ScienceAnswerValue) {
    setSubmission((old) => ({ ...old, [activeStage.id]: { ...(old[activeStage.id] ?? {}), [field.id]: value } }));
  }
  function checkStage() {
    setCheckedStageIds((old) => old.includes(activeStage.id) ? old : [...old, activeStage.id]);
    const next = scenario.stages.find((stage) => !completed.has(stage.id) && stage.id !== activeStage.id && (stage.dependsOn ?? []).every((id) => completed.has(id) || id === activeStage.id && activeEvaluation?.success));
    if (activeEvaluation?.success && next) setActiveStageId(next.id);
  }
  function finish() {
    if (!evaluation.success || submitted) return;
    const endedAt = new Date().toISOString();
    onComplete({ id: runId(), kind: "science", caseId: scenario.id, title: scenario.title, level: scenario.level === "A2+" ? "A2" : scenario.level, startedAt: startedAt.current, endedAt, success: true, score: 450, maxScore: 450, path: evaluation.completedStageIds, decisions: [], metadata: { pathLevel: scenario.courseLevel, localScore: evaluation.score, stages: scenario.stages.length } });
    setSubmitted(true);
  }

  return <main className="science-root science-runner" style={{ "--science-accent": scenario.accent } as React.CSSProperties}><style>{css}</style><header className="science-header"><button onClick={onBack}><ArrowLeft size={19} /></button><div><span>{scenario.eyebrow} · {scenario.level}</span><h1>{scenario.title}</h1><p>{scenario.description}</p></div></header><div className="science-lab"><aside className="science-manual"><section><span>FORMÅL</span><p>{scenario.instructionPane.objective}</p><small>{scenario.instructionPane.context}</small></section><ol>{scenario.instructionPane.procedure.map((step, index) => <li key={step}><b>{index + 1}</b>{step}</li>)}</ol>{scenario.instructionPane.manual.map((section) => <details key={section.id} open={section === scenario.instructionPane.manual[0]}><summary>{section.title}</summary><p>{section.body}</p>{section.formula && <code>{section.formula}</code>}{section.warning && <strong>{section.warning}</strong>}</details>)}<details><summary>Miniordbog</summary>{scenario.instructionPane.glossary.map((entry) => <p key={entry.danish}><b>{entry.danish}</b> — {entry.english}</p>)}</details></aside><section className="science-workspace"><WorkspaceVisual scenario={scenario} /><nav>{scenario.stages.map((stage, index) => { const locked = (stage.dependsOn ?? []).some((id) => !completed.has(id)); return <button className={`${activeStage.id === stage.id ? "active" : ""} ${completed.has(stage.id) ? "done" : ""}`} disabled={locked} onClick={() => setActiveStageId(stage.id)} key={stage.id}>{completed.has(stage.id) ? <Check size={13} /> : index + 1}<span>{stage.title}</span></button>; })}</nav><article><span>AKTIV ETAPE</span><h2>{activeStage.title}</h2><p>{activeStage.instruction}</p><small>{activeStage.workspacePrompt}</small><div className="science-fields">{activeStage.fields.map((field) => <ScienceField key={field.id} field={field} value={submission[activeStage.id]?.[field.id]} onChange={(value) => update(field, value)} />)}</div>{checkedStageIds.includes(activeStage.id) && <div className={activeEvaluation?.success ? "science-feedback good" : "science-feedback bad"}>{activeEvaluation?.success ? activeStage.solutionExplanation : "Resultatet holder endnu ikke. Kontrollér enheder, rækkefølge og manualens tolerance."}</div>}<footer><span>{evaluation.completedStageIds.length}/{scenario.stages.length} etaper · {Math.round(evaluation.score * 100)}%</span><button onClick={evaluation.success ? finish : checkStage}>{submitted ? "Registreret" : evaluation.success ? "Aflever rapport" : "Kontrollér etape"}</button></footer></article></section></div></main>;
}

function ScienceField({ field, value, onChange }: { field: ScienceAnswerField; value: ScienceAnswerValue | undefined; onChange: (value: ScienceAnswerValue) => void }) {
  if (field.kind === "number") return <label><span>{field.label} <em>{field.unit}</em></span><input value={typeof value === "string" || typeof value === "number" ? value : ""} onChange={(event) => onChange(event.target.value)} placeholder={`Tal i ${field.unit}`} /></label>;
  if (field.kind === "choice") return <label><span>{field.label}</span><select value={typeof value === "string" ? value : ""} onChange={(event) => onChange(event.target.value)}><option value="">Vælg …</option>{field.options.map((option) => <option value={option.id} key={option.id}>{option.label}</option>)}</select></label>;
  const selected = Array.isArray(value) ? value : [];
  return <fieldset><legend>{field.label}</legend>{field.options.map((option) => <label key={option.id}><input type="checkbox" checked={selected.includes(option.id)} onChange={() => onChange(selected.includes(option.id) ? selected.filter((id) => id !== option.id) : [...selected, option.id])} />{option.label}</label>)}</fieldset>;
}

function WorkspaceVisual({ scenario }: { scenario: ScienceScenarioCase }) {
  const workspace = scenario.workspace;
  if (workspace.kind === "resistor-board") return <div className="science-visual resistor-visual"><CircuitBoard size={34} />{workspace.resistors.map((resistor) => <div key={resistor.id}><span>{resistor.label}</span><i>{resistor.bands.map((band) => <b className={`band-${band}`} key={band} />)}</i></div>)}</div>;
  if (workspace.kind === "circuit") return <div className="science-visual circuit-visual"><CircuitBoard size={38} /><strong>{workspace.target.label}: {workspace.target.value} {workspace.target.unit}</strong><div>{workspace.components.map((item) => <span key={item.id}>{item.label}</span>)}</div></div>;
  if (workspace.kind === "measurement-bench") return <div className="science-visual meter-visual"><Ruler size={40} /><div>{workspace.readings.map((value) => <i style={{ height: `${30 + value / Math.max(...workspace.readings) * 80}px` }} key={value}><b>{value}</b></i>)}</div></div>;
  if (workspace.kind === "lever") return <div className="science-visual lever-visual"><div>{workspace.loads.map((load) => <span key={load.id} style={{ left: `${20 + (load.positionM ?? load.adjustableSlotsM?.[0] ?? 0) * 12}%` }}>{load.massKg} kg</span>)}</div><i /><b /></div>;
  if (workspace.kind === "density-tank") return <div className="science-visual tank-visual"><FlaskConical size={52} /><div>{workspace.samples.map((sample) => <span key={sample.id}>{sample.label}<b>{sample.massG} g / {sample.volumeCm3} cm³</b></span>)}</div></div>;
  return <div className="science-visual thermal-visual"><Thermometer size={48} /><div>{workspace.layers.map((layer) => <i style={{ background: layer.color, width: `${Math.max(20, layer.thicknessM * 800)}px` }} title={layer.label} key={layer.id} />)}</div><strong>{workspace.insideTemperatureC}°C → {workspace.outsideTemperatureC}°C</strong></div>;
}

const css = `
.science-root{min-height:100%;padding:26px;background:radial-gradient(circle at 88% 5%,color-mix(in srgb,var(--science-accent,#55c6b0) 12%,transparent),transparent 36%),var(--paper);color:var(--ink)}.science-header{max-width:1280px;margin:0 auto 22px;display:flex;align-items:center;gap:16px}.science-header>button{width:44px;height:44px;border:1px solid var(--line);border-radius:13px;background:var(--surface);color:var(--ink)}.science-header span{font-size:8px;font-weight:850;letter-spacing:.12em;color:var(--science-accent,#55c6b0)}.science-header h1{margin:4px 0;font-size:29px}.science-header p{margin:0;color:var(--muted);font-size:11px}
.science-grid{max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.science-grid>button{--science-accent:#55c6b0;text-align:left;min-height:220px;padding:24px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(140deg,var(--surface),color-mix(in srgb,var(--science-accent) 8%,var(--surface)));color:var(--ink)}.science-grid svg,.science-grid span{color:var(--science-accent)}.science-grid span{display:block;margin:16px 0 5px;font-size:8px;letter-spacing:.1em}.science-grid h2{margin:0}.science-grid p{color:var(--muted);font-size:10px;line-height:1.55}.science-grid footer{display:flex;align-items:center;gap:6px;margin-top:17px;font-size:10px;font-weight:800}
.science-lab{max-width:1350px;margin:auto;display:grid;grid-template-columns:380px minmax(0,1fr);gap:18px}.science-manual{display:grid;align-content:start;gap:10px}.science-manual>section,.science-manual>ol,.science-manual details{padding:16px;border:1px solid var(--line);border-radius:15px;background:var(--surface)}.science-manual>section span{font-size:8px;color:var(--science-accent);font-weight:850}.science-manual p,.science-manual small,.science-manual li{font-size:10px;line-height:1.55;color:var(--muted)}.science-manual>section p{color:var(--ink);font-weight:700}.science-manual ol{list-style:none;display:grid;gap:9px}.science-manual li{display:grid;grid-template-columns:23px 1fr;gap:8px}.science-manual li b{width:22px;height:22px;display:grid;place-items:center;border-radius:50%;background:color-mix(in srgb,var(--science-accent) 16%,var(--surface));color:var(--science-accent)}.science-manual summary{cursor:pointer;font-size:11px;font-weight:800}.science-manual code{display:block;padding:9px;border-radius:8px;background:var(--paper);font-size:9px}.science-manual details>strong{display:block;color:#e17d72;font-size:9px}
.science-workspace{display:grid;align-content:start;gap:12px}.science-visual{min-height:230px;padding:24px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(135deg,#1f2930,#15201f);color:#daf1eb;overflow:hidden}.science-workspace nav{display:flex;gap:7px}.science-workspace nav button{display:flex;gap:7px;align-items:center;padding:9px 12px;border:1px solid var(--line);border-radius:9px;background:var(--surface);color:var(--muted);font-size:9px}.science-workspace nav button.active{border-color:var(--science-accent);color:var(--ink)}.science-workspace nav button.done{color:var(--science-accent)}.science-workspace article{padding:22px;border:1px solid var(--line);border-radius:18px;background:var(--surface)}.science-workspace article>span{font-size:8px;color:var(--science-accent);font-weight:850}.science-workspace article h2{margin:6px 0}.science-workspace article>p,.science-workspace article>small{color:var(--muted);font-size:10px;line-height:1.55}.science-fields{display:grid;gap:10px;margin:18px 0}.science-fields>label{display:grid;gap:5px}.science-fields label>span,.science-fields legend{font-size:9px;font-weight:750}.science-fields em{color:var(--science-accent)}.science-fields input,.science-fields select{height:43px;padding:0 11px;border:1px solid var(--line);border-radius:9px;background:var(--paper);color:var(--ink)}.science-fields fieldset{display:grid;gap:7px;border:1px solid var(--line);border-radius:10px}.science-fields fieldset label{display:flex;gap:7px;font-size:10px}.science-fields fieldset input{height:auto}.science-feedback{padding:12px;border-radius:10px;font-size:10px;line-height:1.45}.science-feedback.good{background:#203a35;color:#77d8c1}.science-feedback.bad{background:#3b292c;color:#f1a29b}.science-workspace article footer{display:flex;justify-content:space-between;align-items:center;margin-top:17px}.science-workspace article footer span{color:var(--muted);font-size:9px}.science-workspace article footer button{padding:11px 15px;border:0;border-radius:9px;background:var(--science-accent);color:#142520;font-weight:850}
.resistor-visual>div{display:flex;align-items:center;gap:13px;margin:14px 0}.resistor-visual>div>span{width:80px;font-size:10px}.resistor-visual i{display:flex;gap:8px;padding:7px 14px;border-radius:16px;background:#d5b77e}.resistor-visual b{width:8px;height:33px;background:#222}.band-brown{background:#6f452e!important}.band-red{background:#d84e48!important}.band-orange{background:#e99638!important}.band-yellow{background:#eadb4c!important}.band-green{background:#47a765!important}.band-blue{background:#467bca!important}.band-violet{background:#8553aa!important}.band-grey{background:#8b9295!important}.band-white{background:#eee!important}.band-gold{background:#c6a238!important}.band-silver{background:#aaa!important}.circuit-visual>div,.tank-visual>div{display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.circuit-visual span,.tank-visual span{padding:11px;border:1px solid #42645d;border-radius:9px;font-size:9px}.tank-visual span b{display:block;color:#74cfb9}.meter-visual>div{height:150px;display:flex;align-items:end;gap:12px;margin-top:10px}.meter-visual i{width:34px;background:#55c6b0;border-radius:5px 5px 0 0;position:relative}.meter-visual b{position:absolute;bottom:100%;font-size:8px}.lever-visual>div{height:110px;position:relative}.lever-visual span{position:absolute;bottom:0;padding:8px;background:#d7a655;color:#1c211f;border-radius:7px;font-size:9px}.lever-visual>i{display:block;height:8px;background:#8d7251}.lever-visual>b{display:block;width:0;margin:auto;border-left:35px solid transparent;border-right:35px solid transparent;border-bottom:70px solid #536761}.thermal-visual>div{display:flex;height:110px;margin:20px 0}.thermal-visual i{height:100%}
@media(max-width:950px){.science-lab{grid-template-columns:1fr}.science-grid{grid-template-columns:1fr}.science-root{padding:15px}.science-workspace nav{overflow:auto}}
`;
