import type { DialogueCharacter } from "./scenarioData";

export const dialogueContinuationEpisodes: DialogueCharacter[] = [
  {
    id: "freja",
    name: "Freja",
    age: 24,
    archetype: "Intens & jaloux",
    portrait: "/characters/freja.png",
    color: "#b4557b",
    psychology: "Hun mærker afstand hurtigt. Konkrete aftaler beroliger bedre end adgang til alt.",
    rule: "Vær varm og tydelig; forklar grænsen uden at gøre den til en straf.",
    case: {
      id: "dialogue-freja-boundaries",
      title: "Grænser ved midnat",
      level: "B1",
      location: "Din opgang · 00.14",
      premise: "Freja vil have din live-position hele natten, efter at du kom senere hjem end planlagt.",
      objective: "Skab tryghed uden at aflevere konstant adgang til din position eller telefon.",
      startNode: "fb-1",
      successTrust: 72,
      dangerLimit: 90,
      nodes: {
        "fb-1": {
          id: "fb-1",
          speaker: "Freja",
          line: "Du skrev, at du var hjemme klokken tolv. Hvorfor kan jeg ikke bare se din position, når jeg bliver urolig?",
          stage: "Hun står under gadelygten med armene over kors.",
          choices: [
            { id: "fb-1-clear", text: "Jeg kom for sent og burde have skrevet. Jeg deler gerne min plan, men ikke min position hele natten.", next: "fb-2-open", trust: 17, tension: -9, insight: "Du tager ansvar og adskiller information fra overvågning.", principle: "Ansvar før grænse." },
            { id: "fb-1-code", text: "Du kan få min kode og min position, hvis du holder op med at spørge.", next: "fb-2-control", trust: 2, tension: 12, insight: "Adgang køber kort stilhed, men gør næste krav lettere.", principle: "Adgang er ikke tillid." },
            { id: "fb-1-dismiss", text: "Det er dit problem, at du bliver urolig.", next: "fb-2-repair", trust: -18, tension: 31, insight: "Du afviser følelsen i stedet for at afvise kontrollen.", principle: "Anerkend følelsen, ikke kravet." },
          ],
        },
        "fb-2-open": {
          id: "fb-2-open",
          speaker: "Freja",
          line: "Hvad skal jeg så gøre næste gang, når du ikke svarer? Bare vente?",
          stage: "Hun sænker stemmen, men holder blikket fast på dig.",
          choices: [
            { id: "fb-2-plan", text: "Hvis jeg bliver mere end femten minutter forsinket, skriver jeg. Hvis jeg ikke kan svare, ringer jeg, så snart jeg kan.", next: "fb-3", trust: 16, tension: -8, insight: "En målbar aftale erstatter gætteriet.", principle: "Gør tryghed konkret." },
            { id: "fb-2-always", text: "Jeg svarer altid med det samme fra nu af.", next: "fb-2-control", trust: 4, tension: 7, insight: "Et absolut løfte kan ikke holdes og skaber en ny test.", principle: "Undgå umulige garantier." },
          ],
        },
        "fb-2-control": {
          id: "fb-2-control",
          speaker: "Freja",
          line: "Godt. Så slå deling til nu, og lad den være tændt indtil i morgen.",
          stage: "Hun rækker hånden frem efter telefonen.",
          choices: [
            { id: "fb-2-control-stop", text: "Nej. Jeg trak et dårligt løfte. Jeg vil gerne lave en aftale om beskeder i stedet.", next: "fb-3", trust: 14, tension: -12, insight: "Du retter eftergivenheden og tilbyder et sundere alternativ.", principle: "Et nej kan repareres varmt." },
            { id: "fb-2-control-give", text: "Fint. Du bestemmer, hvornår jeg må slå den fra.", next: null, trust: -8, tension: 35, insight: "Du gør kontrollen permanent og fjerner din egen grænse.", principle: "Bevar frivillighed." },
          ],
        },
        "fb-2-repair": {
          id: "fb-2-repair",
          speaker: "Freja",
          line: "Så mine følelser betyder altså ingenting for dig?",
          stage: "Hun tager et skridt tilbage mod fortovet.",
          choices: [
            { id: "fb-2-repair-own", text: "Det sagde jeg hårdt. Din uro betyder noget; konstant sporing er bare ikke en løsning, jeg accepterer.", next: "fb-3", trust: 22, tension: -22, insight: "Du reparerer tonen uden at opgive indholdet.", principle: "Reparér tone, behold grænse." },
            { id: "fb-2-repair-blame", text: "Du hører kun det, du vil høre.", next: null, trust: -22, tension: 44, insight: "Et nyt angreb lukker muligheden for en aftale.", principle: "Stop angrebsspiralen." },
          ],
        },
        "fb-3": {
          id: "fb-3",
          speaker: "Freja",
          line: "Én besked ved forsinkelse. Og hvad må jeg spørge om uden at krydse din grænse?",
          stage: "Hun tager sin egen telefon frem for at skrive aftalen ned.",
          choices: [
            { id: "fb-3-mutual", text: "Spørg hvor jeg er på vej hen, og hvornår jeg forventer at være hjemme. Den samme regel gælder for os begge.", next: null, trust: 22, tension: -14, insight: "Spørgsmålet får et konkret område, og reglen bliver gensidig.", principle: "Gensidige regler holder." },
            { id: "fb-3-secret", text: "Du må helst ikke spørge om noget fremover.", next: null, trust: -13, tension: 25, insight: "Total lukkethed skaber ny usikkerhed i stedet for en brugbar grænse.", principle: "En grænse skal kunne bruges." },
          ],
        },
      },
    },
  },
  {
    id: "freja",
    name: "Freja",
    age: 24,
    archetype: "Intens & jaloux",
    portrait: "/characters/freja.png",
    color: "#b4557b",
    psychology: "Hun læser uklare planer som skjult afstand og tester derfor hvert tomrum.",
    rule: "Sig både hvad I gør sammen, og hvilken plads hver person beholder.",
    case: {
      id: "dialogue-freja-weekend",
      title: "En weekend med plads",
      level: "B2",
      location: "Toget mod Aarhus · 17.38",
      premise: "En fælles weekend kolliderer med dit planlagte møde med en gammel ven.",
      objective: "Forhandl en plan med nærhed, privat tid og realistiske forventninger.",
      startNode: "fw-1",
      successTrust: 74,
      dangerLimit: 89,
      nodes: {
        "fw-1": {
          id: "fw-1",
          speaker: "Freja",
          line: "Du sagde, at det var vores weekend. Hvorfor står der pludselig ‘Emil, lørdag klokken tre’ i kalenderen?",
          stage: "Landskabet glider forbi ruden, mens hun vender skærmen mod dig.",
          choices: [
            { id: "fw-1-context", text: "Jeg burde have nævnt det før. Emil er kun i byen den dag, og jeg vil gerne se ham i en time. Resten af planen ændrer sig ikke.", next: "fw-2-plan", trust: 16, tension: -8, insight: "Du forklarer undtagelsen og dens faktiske størrelse.", principle: "Navngiv omfanget." },
            { id: "fw-1-cancel", text: "Jeg aflyser ham. Weekenden er kun din.", next: "fw-2-sacrifice", trust: 5, tension: -3, insight: "Et hurtigt offer kan blive til skjult modvilje og en ny kontrolregel.", principle: "Forhandl før du ofrer." },
            { id: "fw-1-private", text: "Min kalender er privat. Du skal ikke kommentere den.", next: "fw-2-distance", trust: -17, tension: 30, insight: "Privatliv bliver brugt som mur, selv om planen påvirker jer begge.", principle: "Privatliv fritager ikke for koordinering." },
          ],
        },
        "fw-2-plan": {
          id: "fw-2-plan",
          speaker: "Freja",
          line: "Og hvad skal jeg lave alene i den time?",
          stage: "Hun spørger skarpt, men har ikke afvist planen.",
          choices: [
            { id: "fw-2-choice", text: "Det bestemmer du. Vi kan også flytte vores museumsbesøg, så du får en hel eftermiddag til noget, du selv vælger.", next: "fw-3", trust: 15, tension: -9, insight: "Du giver plads uden at programmere hendes alenetid.", principle: "Plads kræver selvbestemmelse." },
            { id: "fw-2-wait", text: "Du kan vente på caféen ved siden af, så jeg ved, hvor du er.", next: "fw-2-distance", trust: -6, tension: 17, insight: "Du beder om frihed, men giver ikke den samme frihed tilbage.", principle: "Frihed skal være gensidig." },
          ],
        },
        "fw-2-sacrifice": {
          id: "fw-2-sacrifice",
          speaker: "Freja",
          line: "Hvis du virkelig vil se ham, kommer du så til at bebrejde mig, at du aflyste?",
          stage: "Spørgsmålet lander roligere end forventet.",
          choices: [
            { id: "fw-2-sacrifice-honest", text: "Det kunne jeg komme til. Lad os finde en plan, hvor jeg ser ham kort, og vi beskytter vores tid sammen.", next: "fw-3", trust: 20, tension: -13, insight: "Du opdager prisen ved et falsk offer og vender tilbage til forhandling.", principle: "Undgå skjult gæld." },
            { id: "fw-2-sacrifice-deny", text: "Nej, jeg vil aldrig savne noget, når jeg er sammen med dig.", next: null, trust: -10, tension: 28, insight: "Det absolutte udsagn lyder konstrueret og kan ikke holde.", principle: "Nærhed behøver ikke udslette andre behov." },
          ],
        },
        "fw-2-distance": {
          id: "fw-2-distance",
          speaker: "Freja",
          line: "Du vil have plads, men jeg må åbenbart bare tilpasse mig. Hvor er vores fælles plan?",
          stage: "Hun lægger telefonen væk og vender sig mod gangen.",
          choices: [
            { id: "fw-2-distance-repair", text: "Du har ret i, at jeg ikke koordinerede. Jeg vil beholde mødet, men vi beslutter resten af lørdagen sammen nu.", next: "fw-3", trust: 22, tension: -21, insight: "Du anerkender procesfejlen uden at slette dit behov.", principle: "Reparér processen." },
            { id: "fw-2-distance-exit", text: "Så kan vi lige så godt tage hjem igen.", next: null, trust: -24, tension: 47, insight: "Truslen gør en kalenderkonflikt til et spørgsmål om hele relationen.", principle: "Undgå totale konsekvenser." },
          ],
        },
        "fw-3": {
          id: "fw-3",
          speaker: "Freja",
          line: "Fint. Hvad skriver vi så i kalenderen, så ingen skal gætte?",
          stage: "Hun åbner en tom fælles note.",
          choices: [
            { id: "fw-3-balanced", text: "Lørdag formiddag er vores. Klokken tre ser jeg Emil i en time. Derefter vælger vi aftensmad sammen, og søndag er uden faste planer.", next: null, trust: 23, tension: -14, insight: "Planen markerer fælles tid, egen tid og åben tid.", principle: "Tre slags tid kan sameksistere." },
            { id: "fw-3-vague", text: "Vi finder bare ud af det undervejs.", next: null, trust: -12, tension: 22, insight: "Uklare ord genskaber præcis det tomrum, konflikten begyndte i.", principle: "Afslut med en synlig aftale." },
          ],
        },
      },
    },
  },
  {
    id: "maja",
    name: "Maja",
    age: 26,
    archetype: "Perfektionist & people-pleaser",
    portrait: "/characters/maja.png",
    color: "#72a88c",
    psychology: "Hun siger ja for tidligt og forsøger derefter at skjule, at opgaven er blevet for stor.",
    rule: "Gør kapacitet synlig, og hjælp hende med at bede om en prioritering.",
    case: {
      id: "dialogue-maja-opening",
      title: "Åbning før åbningstid",
      level: "B1",
      location: "Kaffebaren · 06.47",
      premise: "Maja har lovet at åbne caféen, skrive skilte og færdiggøre en menu på samme tid.",
      objective: "Hjælp Maja med at fordele ansvar uden at overtage hele morgenen.",
      startNode: "mo-1",
      successTrust: 70,
      dangerLimit: 88,
      nodes: {
        "mo-1": {
          id: "mo-1",
          speaker: "Maja",
          line: "Jeg kan godt nå det. Skiltet, menuen, kassen og alle borde. Hvis jeg bare arbejder hurtigere.",
          stage: "Hun har allerede tabt tuschen to gange.",
          choices: [
            { id: "mo-1-list", text: "Lad os skrive opgaverne og tiden ned. Hvad skal være klart, før døren åbner?",
              next: "mo-2-priority", trust: 17, tension: -11, insight: "En liste gør den skjulte overbelastning målbar.", principle: "Synliggør kapaciteten." },
            { id: "mo-1-take", text: "Giv mig det hele. Sæt dig bare ned.", next: "mo-2-takeover", trust: -3, tension: -4, insight: "Du fjerner presset og samtidig hendes ejerskab.", principle: "Støtte er ikke overtagelse." },
            { id: "mo-1-push", text: "Du kan sikkert nå det, hvis du stopper med at stresse.", next: "mo-2-shame", trust: -15, tension: 28, insight: "Du gør stress til en personlig fejl og bevarer den umulige plan.", principle: "Ret planen, ikke personen." },
          ],
        },
        "mo-2-priority": {
          id: "mo-2-priority",
          speaker: "Maja",
          line: "Kassen og bordene skal være klar. Men chefen bad også om den nye menu i morges.",
          stage: "Hun ser på uret og derefter på den halvfærdige tavle.",
          choices: [
            { id: "mo-2-ask", text: "Skriv til chefen: ‘Jeg kan åbne caféen eller færdiggøre menuen først. Hvad prioriterer du?’",
              next: "mo-3", trust: 18, tension: -12, insight: "Du gør konsekvensen tydelig og beder ejeren af opgaven vælge.", principle: "Bed om prioritering." },
            { id: "mo-2-both", text: "Sig, at alt bliver færdigt til tiden.", next: "mo-2-shame", trust: -8, tension: 21, insight: "Et nyt løfte skjuler stadig kapacitetsproblemet.", principle: "Lov ikke usynlig tid." },
          ],
        },
        "mo-2-takeover": {
          id: "mo-2-takeover",
          speaker: "Maja",
          line: "Selvfølgelig. Du gør det nok også bedre. Skal jeg bare gå om bagved?",
          stage: "Hun tager forklædet af, selv om hun kender åbnerutinen bedst.",
          choices: [
            { id: "mo-2-return", text: "Nej, det var for meget. Du åbner kassen; jeg tørrer bordene, mens du beder chefen prioritere resten.", next: "mo-3", trust: 19, tension: -14, insight: "Opgaven bliver delt efter kompetence, og Maja beholder styringen.", principle: "Fordel, men overtag ikke." },
            { id: "mo-2-leave", text: "Ja. Jeg kalder, når jeg er færdig.", next: null, trust: -18, tension: 25, insight: "Caféen åbner måske, men relationen og hendes mestring bliver svagere.", principle: "Effektivitet er ikke det eneste mål." },
          ],
        },
        "mo-2-shame": {
          id: "mo-2-shame",
          speaker: "Maja",
          line: "Jeg ved godt, at jeg er langsom. Jeg siger til chefen, at jeg ikke kan klare jobbet.",
          stage: "Hun sletter kladden til beskeden og begynder på en opsigelse.",
          choices: [
            { id: "mo-2-shame-repair", text: "Det handler ikke om, at du er langsom. Fire samtidige opgaver kræver en prioritering. Lad os formulere den sammen.", next: "mo-3", trust: 23, tension: -24, insight: "Du flytter problemet fra identitet til arbejdsplan.", principle: "Adskil person og kapacitet." },
            { id: "mo-2-shame-confirm", text: "Måske er jobbet faktisk for svært for dig.", next: null, trust: -26, tension: 46, insight: "Du bekræfter katastrofetolkningen uden at undersøge opgaven.", principle: "Undersøg før du dømmer." },
          ],
        },
        "mo-3": {
          id: "mo-3",
          speaker: "Maja",
          line: "Chefen svarer: ‘Åbn først. Menuen kan vente til ni.’ Hvad gør vi nu?",
          stage: "Skuldrene falder en smule, og hun binder forklædet igen.",
          choices: [
            { id: "mo-3-split", text: "Du tager kassen, som du kender. Jeg gør bordene klar. Klokken ni ser vi på menuen sammen.", next: null, trust: 22, tension: -15, insight: "Planen har ejerskab, støtte og et tydeligt senere tidspunkt.", principle: "Afslut med roller og tid." },
            { id: "mo-3-extra", text: "Godt. Så lover vi også, at skiltet er nyt klokken otte.", next: null, trust: -10, tension: 23, insight: "Du fylder den frigjorte plads med endnu et uafklaret løfte.", principle: "Beskyt den nye prioritering." },
          ],
        },
      },
    },
  },
  {
    id: "maja",
    name: "Maja",
    age: 26,
    archetype: "Perfektionist & people-pleaser",
    portrait: "/characters/maja.png",
    color: "#72a88c",
    psychology: "Hun hører bred kritik som en dom over hele sit arbejde.",
    rule: "Oversæt vurderinger til afgrænsede observationer, spørgsmål og næste handling.",
    case: {
      id: "dialogue-maja-critique",
      title: "Den svære feedback",
      level: "B2",
      location: "Designstudiet · 13.26",
      premise: "En kunde kalder Majas design ‘uroligt og gammeldags’ uden at forklare hvorfor.",
      objective: "Gør vag kritik anvendelig uden at benægte den eller gøre Maja til problemet.",
      startNode: "mc-1",
      successTrust: 73,
      dangerLimit: 89,
      nodes: {
        "mc-1": {
          id: "mc-1",
          speaker: "Maja",
          line: "‘Uroligt og gammeldags.’ Det betyder vel, at hele retningen var forkert fra begyndelsen.",
          stage: "Hun har markeret alle sider med rødt, også dem kunden ikke nævnte.",
          choices: [
            { id: "mc-1-scope", text: "Vi ved endnu ikke, om kommentaren gælder hele retningen. Hvilke konkrete elementer pegede kunden på?",
              next: "mc-2-evidence", trust: 18, tension: -11, insight: "Du stopper generaliseringen og leder efter observationer.", principle: "Afgræns udsagnet." },
            { id: "mc-1-deny", text: "Kunden tager fejl. Designet er perfekt.", next: "mc-2-defense", trust: 2, tension: 9, insight: "Tomt forsvar gør kritikken mindre undersøgelig, ikke mindre virkelig.", principle: "Forsvar er ikke analyse." },
            { id: "mc-1-agree", text: "Ja, vi bør nok begynde helt forfra.", next: "mc-2-collapse", trust: -16, tension: 29, insight: "Du accepterer en maksimal konklusion fra minimal information.", principle: "Match ændringen til evidensen." },
          ],
        },
        "mc-2-evidence": {
          id: "mc-2-evidence",
          speaker: "Maja",
          line: "De nævnte den tætte forside og sagde, at knapperne mindede om den gamle løsning.",
          stage: "Hun finder kundens noter frem i stedet for at se på de røde markeringer.",
          choices: [
            { id: "mc-2-question", text: "Så kan vi spørge, om ‘uroligt’ betyder tæt informationshierarki, og om ‘gammeldags’ gælder knappernes form.", next: "mc-3", trust: 19, tension: -12, insight: "To adjektiver bliver til to efterprøvelige hypoteser.", principle: "Operationalisér kritikken." },
            { id: "mc-2-redesign", text: "Lad os ændre farver, fonte, billeder og navigation med det samme.", next: "mc-2-collapse", trust: -7, tension: 20, insight: "Du ændrer flere variable, end feedbacken kan begrunde.", principle: "Skift én begrundet ting ad gangen." },
          ],
        },
        "mc-2-defense": {
          id: "mc-2-defense",
          speaker: "Maja",
          line: "Men hvis vi bare forsvarer det, lærer jeg stadig ikke, hvad de reagerede på.",
          stage: "Hun vender skærmen tilbage mod jer begge.",
          choices: [
            { id: "mc-2-defense-correct", text: "Du har ret. Lad os bede dem pege på ét sted for hvert ord og beskrive den ønskede virkning.", next: "mc-3", trust: 22, tension: -16, insight: "Du slipper forsvaret og beder om eksempler plus mål.", principle: "Eksempel + ønsket virkning." },
            { id: "mc-2-defense-attack", text: "Så må kunden lære at give ordentlig feedback.", next: null, trust: -18, tension: 37, insight: "Angrebet beskytter jer kort, men gør næste samtale mere låst.", principle: "Forbedr spørgsmålet, ikke fjendebilledet." },
          ],
        },
        "mc-2-collapse": {
          id: "mc-2-collapse",
          speaker: "Maja",
          line: "Jeg kan have en helt ny version i morgen, hvis jeg arbejder hele natten.",
          stage: "Hun åbner allerede en tom fil.",
          choices: [
            { id: "mc-2-collapse-stop", text: "Stop. Vi ændrer ikke alt uden belæg. Først får vi to konkrete eksempler og bekræfter målet.", next: "mc-3", trust: 23, tension: -23, insight: "Du stopper overarbejde ved at definere den manglende information.", principle: "Ingen total løsning før et afgrænset problem." },
            { id: "mc-2-collapse-night", text: "God idé. Send mig filen i morgen tidlig.", next: null, trust: -25, tension: 45, insight: "Du belønner katastrofetolkningen med en nat uden grænser.", principle: "Tidspres er også en designbegrænsning." },
          ],
        },
        "mc-3": {
          id: "mc-3",
          speaker: "Maja",
          line: "Kunden svarer: ‘Forsiden mangler luft, og de grå knapper ligner det gamle system.’ Hvad er vores næste version?",
          stage: "To præcise kommentarer står nu alene på tavlen.",
          choices: [
            { id: "mc-3-test", text: "Vi laver én variant med mere luft og én ny knapstil. Resten holdes fast, så kunden kan sammenligne.", next: null, trust: 23, tension: -14, insight: "Forslaget tester netop de to påstande uden at skjule årsagen.", principle: "Byg en sammenlignelig ændring." },
            { id: "mc-3-polish", text: "Vi gør bare hele siden mere moderne.", next: null, trust: -12, tension: 21, insight: "‘Mere moderne’ gentager vagheden i stedet for at løse den.", principle: "Afslut med observerbare ændringer." },
          ],
        },
      },
    },
  },
  {
    id: "nora",
    name: "Nora",
    age: 28,
    archetype: "Analytisk & bevogtet",
    portrait: "/characters/nora.png",
    color: "#5d82bc",
    psychology: "Hun reagerer på upræcise præmisser og spørgsmål, der foregiver neutralitet.",
    rule: "Definér variablen, fjern det indbyggede svar, og giv plads til korrektion.",
    case: {
      id: "dialogue-nora-interview",
      title: "Interviewet på kajen",
      level: "B2",
      location: "Havnekajen · 10.03",
      premise: "Et interview med en restauratør skal begynde, men dit første spørgsmål indeholder allerede konklusionen.",
      objective: "Formulér spørgsmål, der er præcise uden at lægge svaret i munden på kilden.",
      startNode: "ni-1",
      successTrust: 74,
      dangerLimit: 88,
      nodes: {
        "ni-1": {
          id: "ni-1",
          speaker: "Nora",
          line: "Dit første spørgsmål er: ‘Hvorfor har de urimelige havneafgifter tvunget dig til at fyre ansatte?’ Hvad ved vi faktisk?",
          stage: "Optagerens røde lampe venter på bordet.",
          choices: [
            { id: "ni-1-facts", text: "Vi ved, at afgiften steg, og at bemandingen faldt. Vi ved ikke, om det ene forårsagede det andet.", next: "ni-2-neutral", trust: 20, tension: -12, insight: "Du skelner observation fra årsag.", principle: "Adskil korrelation og forklaring." },
            { id: "ni-1-obvious", text: "Sammenhængen er åbenlys, så spørgsmålet sparer tid.", next: "ni-2-leading", trust: -15, tension: 27, insight: "Et sandsynligt svar er stadig ikke dokumenteret årsag.", principle: "Sandsynlighed er ikke evidens." },
            { id: "ni-1-soft", text: "Jeg kan bare sige ‘synes du måske’, så bliver det neutralt.", next: "ni-2-wording", trust: -7, tension: 15, insight: "Høflige markører fjerner ikke den indbyggede præmis.", principle: "Neutralitet ligger i strukturen." },
          ],
        },
        "ni-2-neutral": {
          id: "ni-2-neutral",
          speaker: "Nora",
          line: "Godt. Giv mig et spørgsmål, der undersøger forbindelsen uden at antage den.",
          stage: "Hun skubber notesbogen over til dig.",
          choices: [
            { id: "ni-2-open", text: "Hvilke forhold havde størst betydning for, at I reducerede bemandingen?",
              next: "ni-3", trust: 19, tension: -11, insight: "Kilden kan nævne afgiften, andre forhold eller afvise præmissen.", principle: "Åbn årsagsrummet." },
            { id: "ni-2-confirm", text: "Var havneafgiften den vigtigste grund til fyringerne?",
              next: "ni-2-wording", trust: -5, tension: 14, insight: "Spørgsmålet er bedre, men fremhæver stadig én forklaring før de andre.", principle: "Start bredt, afgræns bagefter." },
          ],
        },
        "ni-2-leading": {
          id: "ni-2-leading",
          speaker: "Nora",
          line: "Hvis kilden siger ja, har vi så lært noget — eller bare fået vores ord gentaget?",
          stage: "Hun slukker optageren igen.",
          choices: [
            { id: "ni-2-leading-repair", text: "Kun det sidste. Jeg spørger åbent om beslutningen og følger derefter op på afgiften.", next: "ni-3", trust: 24, tension: -21, insight: "Du ændrer både rækkefølge og evidensværdi.", principle: "Åbent først, test bagefter." },
            { id: "ni-2-leading-insist", text: "Et ja er stadig et citat, og citater er dokumentation.", next: null, trust: -24, tension: 43, insight: "Et citat dokumenterer udsagnet, ikke kvaliteten af spørgsmålet eller årsagen.", principle: "Citat er ikke automatisk bevis." },
          ],
        },
        "ni-2-wording": {
          id: "ni-2-wording",
          speaker: "Nora",
          line: "Du har gjort tonen blødere. Hvor gemmer antagelsen sig stadig?",
          stage: "Hun understreger ordene ‘afgiften’ og ‘grunden’.",
          choices: [
            { id: "ni-2-wording-find", text: "Jeg har stadig valgt årsagen på forhånd. Jeg skal først spørge, hvad der påvirkede beslutningen.", next: "ni-3", trust: 23, tension: -18, insight: "Du finder præmissen under den høflige overflade.", principle: "Fjern den valgte årsag." },
            { id: "ni-2-wording-hide", text: "Jeg tilføjer ‘hvis overhovedet’, så kan spørgsmålet ikke være ledende.", next: null, trust: -19, tension: 35, insight: "Et forbehold til sidst ophæver ikke hele spørgsmålets fokus.", principle: "Omskriv, ikke kosmetisér." },
          ],
        },
        "ni-3": {
          id: "ni-3",
          speaker: "Nora",
          line: "Restauratøren siger, at energipriser og færre gæster betød mere end afgiften. Hvad spørger du nu?",
          stage: "Optageren kører, og svaret modsiger jeres oprindelige vinkel.",
          choices: [
            { id: "ni-3-follow", text: "Kan du beskrive, hvordan de tre forhold hver især påvirkede beslutningen, og hvilke tal du bygger vurderingen på?",
              next: null, trust: 24, tension: -15, insight: "Du følger kildens forklaring og beder samtidig om efterprøveligt grundlag.", principle: "Følg svaret, og bed om belæg." },
            { id: "ni-3-return", text: "Men afgiften var vel stadig urimelig?",
              next: null, trust: -14, tension: 25, insight: "Du forsøger at få den oprindelige vinkel tilbage efter et modstridende svar.", principle: "Lad evidensen ændre vinklen." },
          ],
        },
      },
    },
  },
  {
    id: "nora",
    name: "Nora",
    age: 28,
    archetype: "Analytisk & bevogtet",
    portrait: "/characters/nora.png",
    color: "#5d82bc",
    psychology: "Hun accepterer fejl, hvis rettelsen er lige så synlig og præcis som den oprindelige påstand.",
    rule: "Navngiv fejlen, dens rækkevidde og hvad der fortsat er sandt.",
    case: {
      id: "dialogue-nora-correction",
      title: "Rettelsen på forsiden",
      level: "B2",
      location: "Redaktionen · 07.12",
      premise: "En artikel har forvekslet kommunens forslag med en vedtaget beslutning.",
      objective: "Skriv og placér en rettelse, der genopretter information uden at skjule ansvaret.",
      startNode: "nc-1",
      successTrust: 75,
      dangerLimit: 88,
      nodes: {
        "nc-1": {
          id: "nc-1",
          speaker: "Nora",
          line: "Vi skrev, at havneplanen var vedtaget. Den er kun sendt i høring. Hvad er den præcise fejl?",
          stage: "Morgenens avis ligger åben ved siden af den officielle dagsorden.",
          choices: [
            { id: "nc-1-status", text: "Vi beskrev et forslag som en endelig beslutning og gjorde dermed udfaldet mere sikkert, end kilden tillod.", next: "nc-2-scope", trust: 21, tension: -12, insight: "Du navngiver både kategorifejlen og dens virkning.", principle: "Beskriv fejlens mekanisme." },
            { id: "nc-1-word", text: "Der mangler bare ordet ‘måske’ et sted.", next: "nc-2-minimize", trust: -11, tension: 20, insight: "Fejlen ændrer hele beslutningens status, ikke kun tonen i ét ord.", principle: "Match rettelsen til rækkevidden." },
            { id: "nc-1-source", text: "Kommunen skrev teksten uklart, så ansvaret er deres.", next: "nc-2-blame", trust: -17, tension: 31, insight: "En uklar kilde fritager ikke redaktionen for at kontrollere status.", principle: "Tag ansvar for publiceringen." },
          ],
        },
        "nc-2-scope": {
          id: "nc-2-scope",
          speaker: "Nora",
          line: "Hvor synlig skal rettelsen være? Artiklen lå øverst på forsiden i tre timer.",
          stage: "Trafiktallene viser, at tusindvis allerede har læst den.",
          choices: [
            { id: "nc-2-visible", text: "En tydelig note øverst i artiklen og en forsidelinket rettelse. Samme publikum skal have en reel chance for at se den.", next: "nc-3", trust: 20, tension: -12, insight: "Synligheden følger den oprindelige fejls rækkevidde.", principle: "Rettelsen skal kunne nå læseren." },
            { id: "nc-2-bottom", text: "En note nederst er nok; teksten er jo teknisk set rettet.", next: "nc-2-minimize", trust: -8, tension: 18, insight: "En usynlig rettelse ændrer databasen, men ikke nødvendigvis læserens forståelse.", principle: "Teknisk korrekt er ikke kommunikativt tilstrækkeligt." },
          ],
        },
        "nc-2-minimize": {
          id: "nc-2-minimize",
          speaker: "Nora",
          line: "Hvis læseren kun ser vores korte note, forstår personen så, hvad der var forkert?",
          stage: "Hun sletter formuleringen ‘mindre præcis ordlyd’.",
          choices: [
            { id: "nc-2-minimize-repair", text: "Nej. Vi skal skrive, at planen ikke er vedtaget, men i høring, og at den tidligere version angav det modsatte.", next: "nc-3", trust: 24, tension: -20, insight: "Rettelsen kan stå alene og forklarer forskellen.", principle: "Skriv før og nu." },
            { id: "nc-2-minimize-vague", text: "Vi skriver bare, at artiklen er opdateret.", next: null, trust: -22, tension: 40, insight: "‘Opdateret’ skjuler, om ændringen var kosmetisk eller afgørende.", principle: "Navngiv korrektionen." },
          ],
        },
        "nc-2-blame": {
          id: "nc-2-blame",
          speaker: "Nora",
          line: "Vores navn står på artiklen. Hvilken kontrol sprang vi over?",
          stage: "Hun peger på linjen ‘forslag til offentlig høring’ i originaldokumentet.",
          choices: [
            { id: "nc-2-blame-own", text: "Vi kontrollerede ikke dokumentets formelle status. Det skriver vi i rettelsen og tilføjer kontrollen til vores proces.", next: "nc-3", trust: 25, tension: -23, insight: "Ansvar bliver både offentligt og operationelt.", principle: "Ret teksten og processen." },
            { id: "nc-2-blame-double", text: "Vi bør skrive, at kommunen vildledte os.", next: null, trust: -27, tension: 48, insight: "Du forvandler egen kontrolfejl til en udokumenteret ny anklage.", principle: "Undgå en ny fejl i rettelsen." },
          ],
        },
        "nc-3": {
          id: "nc-3",
          speaker: "Nora",
          line: "Læs den endelige note højt. Den skal være kort, præcis og uden tåge.",
          stage: "Markøren blinker over artiklens første afsnit.",
          choices: [
            { id: "nc-3-full", text: "Rettelse: Vi skrev tidligere, at havneplanen var vedtaget. Det var forkert. Planen er sendt i offentlig høring og er endnu ikke besluttet.", next: null, trust: 25, tension: -15, insight: "Noten angiver den tidligere påstand, fejlen og den korrekte status.", principle: "Påstand + fejl + korrekt information." },
            { id: "nc-3-soft", text: "Præcisering: Havneplanen befinder sig på nuværende tidspunkt i en fortsat proces.", next: null, trust: -16, tension: 26, insight: "Passiv og abstrakt formulering skjuler både fejlen og den aktuelle status.", principle: "Undgå tåge i en rettelse." },
          ],
        },
      },
    },
  },
];

export const dialogueContinuationCases = dialogueContinuationEpisodes.map((episode) => episode.case);

